### ISSUE TITLE
lib fails all the user's channels on transition to connecting/disconnected if queueMessages is disabled?

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-cocoa#1004]
https://github.com/ably/ably-cocoa/blob/f0e4018040bf0c4b014e2fb6907fb5d75016d8df/Source/ARTRealtime.m#L701-L739

This is in transitionSideEffects. The implemented logic appears to be that if sendEvents and queueEvents are both false, and it's not in the closing, closed, or suspended states, then it should set all the channels to failed. Perhaps it's assuming that the only remaining state that it can be in in that branch is the `failed` state; if so this is not a correct assumption because `queueMessages` can be disabled, which will make `shouldSendEvents` and `shouldQueueEvents` both return false in states like `connecting` and `disconnected`.

If I'm reading the code right, the effect of this is to make the queueMessages client option completely unusable, all subsequent operations on any channels that had already been accessed will then fail even once the lib has reconnected after the first time it goes into the connecting or disconnected states

**Comment by QuintinWillison** [comment]
Internal Breadcrumbs: [Slack](https://ably-real-time.slack.com/archives/C030C5YLY/p1584973153034800), [Intercom](https://app.intercom.com/a/apps/ua39m1ld/inbox/inbox/conversation/26069109023)

Expected behaviours, as supplied by @SimonWoolf via Slack: [RTL3](https://docs.ably.io/client-lib-development-guide/features/#RTL3) and [TO3g](https://docs.ably.io/client-lib-development-guide/features/#TO3g).

**Comment by tomczoink** [comment]
<div>Agent Tom Camp linked Freshdesk ticket <a href="https://ably.freshdesk.com/a/tickets/106205">106205</a> for this issue.</div>
