### ISSUE TITLE
Custom logger not working?

### ISSUE THREAD

**Issue by SpencerCDixon** [ably/ably-cocoa#1010]
### Which version of the Ably SDK are you using? 
E.g. `1.21.1`

### On which platform does the issue happen? 
macOS 10.14/15

### Are you using Carthage? 
0.34.0

### Which version of Xcode are you using? 
11.3

### What did you do?
Using a custom logger doesn't appear to be working. I'm probably doing something really dumb and silly so I apologize in advance.

Here is my code:

Custom logger with a breakpoint
![Screen Shot 2020-04-09 at 12 53 16 PM](https://user-images.githubusercontent.com/7471018/78920402-5255ea00-7a61-11ea-9879-ae809edd8a19.png)

Create instance 
```
...
self.logHandler = MyLogger()
...
```

Setting in my client options:
```
let options = ARTClientOptions()
options.logLevel = .verbose
options.logHandler = self.logHandler
let ably = ARTRealtime(options: options)
```

Logging continues to happen to console and my breakpoint in my custom logger never gets hit.

Something obvious I'm missing or is this a regression in the library?

EDIT:
I forked the project and added NSLog's in the ARTRest initWithOptions. I'm seeing my custom logger get set just not receiving any messages :(

**Comment by QuintinWillison** [comment]
Hi @SpencerCDixon - I've just had a go myself and you're on to something! This looks like a bug.

You're correctly overriding the method we expose in our interface (being `log:withLevel`) but the internal implementation appears to be circumventing your override and calling an internal method instead.

I'll get this fixed but in the meantime I was able (in Objective-C for the moment) prove that I can get my override called if I implement using the selector `log:level`, not `log:withLevel`. I've not yet tested from Swift but that might help you.

**Comment by SpencerCDixon** [comment]
Thanks Quintin! Let me know when you have a fix! In the meantime, I can try getting the Objective-C solution working

We have some customers having issues with the client getting in an infinite reconnect loop. I need to hook your logger into ours so we can give you debug info to resolve those issues

**Comment by QuintinWillison** [comment]
I've pushed up a tentative fix for you, @SpencerCDixon ... if you wouldn't mind replacing the Ably entry in your `Cartfile` with:

```
github "ably/ably-cocoa" "feature/bugfix-1010"
```

and letting me know if your logger works now?

We can then work on getting a formal release out with this fix next week.

**Comment by SpencerCDixon** [comment]
Good news! The breakpoints are now being hit. Thank you for fixing this so quickly I really appreciate it.

I'll work off your branch until an official release goes out

**Comment by QuintinWillison** [comment]
Thanks for letting me know so quickly, @SpencerCDixon. I'm glad we could be of assistance! 😁

**Comment by QuintinWillison** [comment]
Hi @SpencerCDixon - the release was made this morning: [v1.1.22](https://github.com/ably/ably-cocoa/releases/tag/1.1.22)

Now that [the PR](https://github.com/ably/ably-cocoa/pull/1011) has been merged, the branch has also been deleted. I'm hoping you can simply move to using the release rather than the branch and, thus, that this will cause you no problems. If you do, however, need me to restore the branch temporarily to aid your transition then just let me know.

Thanks for reporting this.
