### ISSUE TITLE
Features Request: callback for failing to get auth token

### ISSUE THREAD

**Issue by SpencerCDixon** [ably/ably-cocoa#1025]
Sorry if this is already possible and I'm missing something obvious!

The use case: 

I set an `authCallback` that the connection will use to authenticate with Ably. The API request to our server succeeds and returns the `TokenRequest`. Then the Ably client uses that TokenRequest to authenticate with y'alls backend. What happens if that next request fails? I have no way of identifying that and doing something useful (like pointing our users to your network support docs for allowing traffic to certain locations).

```
        let options =  ARTClientOptions()
        options.authCallback = { [weak self] _, complete in
            guard let self = self else { return }

            self.apiService.authenticateAbly { (response, error) in
               ... etc ... 
            }
        }

     // What I want: 
     options.authCallbackFailed = { // do something }
```

Thoughts? Am I missing an obvious setting?

**Comment by ricardopereira** [comment]
Hi @SpencerCDixon, thank you for reaching out.

The `authCallback` completion does handle failures: https://github.com/ably/ably-cocoa/blob/a1b04acf3fd2dd6e5c690c0fe9bd30e808b82f3d/Source/ARTAuthOptions.h#L46

You can tell to the instance that the authentication failed by setting the first argument (token details) to nil and the second argument with the error:

```
let options =  ARTClientOptions()
options.authCallback = { [weak self] _, complete in
    guard let self = self else { return }

    self.apiService.authenticateAbly { (response, error) in
       complete(nil, error) //<---
    }
}
```

You can see more examples in our tests: 

https://github.com/ably/ably-cocoa/blob/a8a4a0bb5d25c1ccb52c4befa8d7c8b46fc2a076/Spec/RealtimeClient.swift#L719-L726

Is this clear to you?

**Comment by paddybyers** [comment]
> I'm assuming (and could be very wrong in my understanding so excuse me if so) that you guys then take that `TokenRequest` and use it to do the actual authentication with Ably via `rest.ably.com`

The client uses the  signed `TokenRequest` to obtain a token. You can make this happen explicitly at the client via a call to `ably.auth.requestToken(tokenRequest)`. If that call succeeds, then it proves that (a) the `TokenRequest` is valid, and (b) that the client can reach the Ably endpoint. If that call fails, then there will be an informative error message.

Does that do what you need?

**Comment by SpencerCDixon** [comment]
Yeah that will work! I can do this flow outside the normal client connection just to confirm our users are able to reach Ably properly and traffic isn't being blocked by a firewall. Thanks for helping me talk through this!

**Comment by paddybyers** [comment]
np, good luck :)
