### ISSUE TITLE
Data race in ARTstartHandlingUncaughtExceptions

### ISSUE THREAD

**Issue by SlaunchaMan** [ably/ably-cocoa#1030]
### Which version of the Ably SDK are you using? 
`1.2.0`

### On which platform does the issue happen? 
iOS 13.5

### Are you using Cocoapods? 
`1.9.2`

### Which version of Xcode are you using? 
Xcode 11.5
Build version 11E608c

### What did you do?
Running our app’s test target.

### What did you expect to happen?
The test succeeds.

### What happened instead?
Xcode’s Thread Sanitizer trips on `ARTstartHandlingUncaughtExceptions()`. It seems that the read of `_handlingUncaughtExceptions` followed by the write to it can happen simultaneously on multiple threads.

<img width="1672" alt="image" src="https://user-images.githubusercontent.com/147458/86029597-5a3e7e00-ba01-11ea-9957-470526ad1c81.png">

**Comment by QuintinWillison** [comment]
@SlaunchaMan that fix is released in [v1.2.1](https://github.com/ably/ably-cocoa/releases/tag/1.2.1).

Thanks again for the bug report.
