### ISSUE TITLE
Conflict KSCrashAblyFork

### ISSUE THREAD

**Issue by bcondeskylinedynamics** [ably/ably-cocoa#1068]
Hi

im new to posting issues but i have problem with Ably v1.2.1 paired with Firebase/Storage and Firebase/Firestore in pods, im getting error 'absl/base/internal/inline_variable.h' file not found in KSCrashAblyFork

Any idea how to fix this? Thank you

**Comment by reinshope** [comment]
I'm also having this issue -- any insight would be nice!

**Comment by QuintinWillison** [comment]
Thanks for the reports, @bcondeskylinedynamics and @reinshope ... 
I'm going to have a look at this. Please bear with me.
