### ISSUE TITLE
Push Notification Registration via `ARTPushRegistererDelegate` don't work in iOS 14 when instantiated via @UIApplicationDelegateAdaptor

### ISSUE THREAD

**Issue by yeastplume** [ably/ably-cocoa#1069]
### Which version of the Ably SDK are you using? 
1.2.1

### On which platform does the issue happen? 
iOS 14

### Are you using Carthage? 
No

### Are you using Cocoapods? 
1.9.3

### Which version of Xcode are you using? 
12

### What did you do?
In a pure swift UI iOS 14 project on XCode12, the application delegate is now bound to the main app class via `@UIApplicationDelegateAdaptor`, such as in the following code snippet: 

```
@main
struct MyApp: App {
	@UIApplicationDelegateAdaptor(MyAppDelegate.self) var appDelegate
...
```

Where AppDelegate would look something like:

```
import Ably
import os.log

class MyAppDelegate: NSObject, UIApplicationDelegate, ARTPushRegistererDelegate {
...	
```

Where `ARTPushRegistererDelegate`protocol functions are defined. I believe `UIApplicationDelegateAdaptor` is downcasting `MyAppDelegate` to `UIApplicationDelegate`, causing registration code in `ARTPushActivationStateMachine.m` to fail on the following check:

https://github.com/ably/ably-cocoa/blob/8c2cc498fc49a92dcc058a44dec6fa03b9501842/Source/ARTPushActivationStateMachine.m#L155

```
    if (![delegate conformsToProtocol:@protocol(ARTPushRegistererDelegate)]) {
        [NSException raise:@"ARTPushRegistererDelegate must be implemented on AppDelegate" format:@""];
    }
```

This halts the app with an exception:

```
2020-09-30 22:12:34.610271+0100 Sharehold[46915:1482664] [d2dClient] Connected to Ably Service
2020-09-30 22:12:34.613031+0100 Sharehold[46915:1482839] *** Terminating app due to uncaught exception 'ARTPushRegistererDelegate must be implemented on AppDelegate', reason: ''
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2043a126 __exceptionPreprocess + 242
```

**Comment by QuintinWillison** [comment]
Hello @yeastplume - thanks for the report. I'm going to take a look at this.
