### ISSUE TITLE
Replace Carthage with SPM for Ably Project and test suite

### ISSUE THREAD

**Issue by ricardopereira** [ably/ably-cocoa#1070]
### Context

Regarding https://github.com/Carthage/Carthage/issues/3019, Carthage builds will fail in Xcode 12 when using beta or latest stable, the installation fails with something like: `error: Unable to determine target or target not included`.

We are using Carthage to build our dependencies while developing and running tests. Our customers can use Carthage to add our library to their project.

### The reason

The reason of this issue is the new Xcode 12 behaviour, which Carthage doesn't handle correctly right now. See https://github.com/Carthage/Carthage/issues/3019 for details.

### Current solution

We can wait until Carthage fix the issue or use the Swift Package Manager or CocoaPods. Since we need to add support to Swift Package Manager (https://github.com/ably/ably-cocoa/issues/819), I propose to use SPM in Ably project and test suite.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-543) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
Can be closed if we decide to remove carthage entirely under #1137.
