### ISSUE TITLE
Incorrect import reference?

### ISSUE THREAD

**Issue by reinshope** [ably/ably-cocoa#1072]
After adding the Ably pod to my project, it would not compile due to it being unable to find the file referenced in many files as follows:

`#import "ARTQueuedDealloc.h"`

Replacing all of these instances with this allowed it to compile successfully:

`#import <Ably/ARTQueuedDealloc.h>`

Is there another way around this so I don't have to edit all of those files during any update?

**Comment by QuintinWillison** [comment]
Hi @reinshope ... is this the latest release of Ably? What version of Xcode are you running? Also, which CocoaPods version? Would you be able to share the contents of your Podfile, perhaps with redactions? Thanks.
