### ISSUE TITLE
Enable CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER for project, if possible

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-cocoa#1076]
On updating the project to Xcode 12's recommended settings it suggested enabling this build flag.

But when I enable it we get lots of warnings. It appears to be highlighting issues in private headers, which I find a bit confusing, but I don't have time to investigate now so creating this issue to look later.

<img width="2222" alt="Screenshot 2020-10-07 at 13 25 01" src="https://user-images.githubusercontent.com/8318344/95330771-f13c9100-08a0-11eb-8900-9d49e9cbcd57.png">

┆Issue is synchronized with this [Jira Research](https://ably.atlassian.net/browse/SDK-364) by [Unito](https://www.unito.io)

**Comment by ricardopereira** [comment]
@QuintinWillison I don't know the specifics of the new `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER`. I usually use angle-bracketed (that I assume it's a framework style include) when it's a public header. If it's private then I use double-quoted include.

**Comment by QuintinWillison** [comment]
Yeah, that's the approach I've usually taken too. But that's often felt clunky so I wonder if there's something deeper going on here. Any thoughts on this, @lawrence-forooghian?
