### ISSUE TITLE
Why does Xcode 12 want to change IPHONEOS_DEPLOYMENT_TARGET for iOS from 8.0 to 12.0?

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-cocoa#1077]
Do we need to reassess our baselines?

If I allow Xcode to adjust this setting then we get a whole load of new warnings, indicating that there are some foundation APIs that may have been newly deprecated.

<img width="2228" alt="Screenshot 2020-10-07 at 13 32 57" src="https://user-images.githubusercontent.com/8318344/95331281-acfdc080-08a1-11eb-8a99-ed75a9a52c1f.png">

**Comment by QuintinWillison** [comment]
ok, the plot thickens... now when I try to build with Xcode 12.0.1, with the iOS deployment target set to 8.0, I get:

```
The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0,
but the range of supported deployment target versions is 9.0 to 14.0.99.
```

**Comment by ricardopereira** [comment]
@QuintinWillison Xcode 12.0 doesn't support 8.0 even so Xcode tries to change the minimum deployment to 12. I don't know exactly why but my guess is that Apple is trying to move people with "old" apps to iOS 12.0+ 😄
