### ISSUE TITLE
Potentially insecure usage of the NSURLSession API

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-cocoa#1079]
We use `NSURLSessionConfiguration`'s [`defaultSessionConfiguration`](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1411560-defaultsessionconfiguration) singleton [in ARTURLSessionServerTrust.m](https://github.com/ably/ably-cocoa/blob/1d0d4df4ff4fd816a1e92d3c3b8407b76e5e9114/Source/ARTURLSessionServerTrust.m#L22).

We should be using [`ephemeralSessionConfiguration`](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1410529-ephemeralsessionconfiguration) instead as that "uses no persistent storage for caches, cookies, or credentials".

Additionally we should also be insisting on TLS protocol negotiation at a minimum of version 1.2. Possibly by using `TLSMinimumSupportedProtocol`, though that seems to have been deprecated and replaced with `TLSMinimumSupportedProtocolVersion` but we need to consider using that API cautiously when it comes to backwards compatibility.

When working on this issue please ensure to check other use of `NSURLSession` APIs as, for example, the `sharedSession` singleton is also problematic for the same reasons.

Also, for the purposes of breadcrumbs, [see the question I asked in Slack](https://ably-real-time.slack.com/archives/CB285667N/p1602607075375000) to which @paddybyers responded with:

> all clients should insist on 1.2+

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-366) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
Hi @SpencerWallsworth - sorry for the (very slow!) response but I only just now noticed your comment when I was looking through issues. There is no precise timescale I can provide, however we are looking at ramping up development on this client library in the next couple of months and, as such, this issue is high on the backlog to be worked on then.

**Comment by maratal** [comment]
Also linked to https://github.com/ably-forks/SocketRocket/issues/7
