### ISSUE TITLE
Common crash related to websocket failing with error

### ISSUE THREAD

**Issue by SpencerCDixon** [ably/ably-cocoa#1083]
### Which version of the Ably SDK are you using? 
`1d0d4df4ff4fd816a1e92d3c3b8407b76e5e9114`

### On which platform does the issue happen? 
`macOS`

### Are you using Cocoapods? 
We've added the dep as a submodule 

### Which version of Xcode are you using? 
Xcode 12.2
Build version 12B5025f

### What did you do?
Have a regular crash related to the library and was wondering if other folks also experienced it.

### What happened instead?

Here is a stack trace of where the crash is occurring. 

```
Crashed: io.ably.main
0  libdispatch.dylib              0x7fff7299517c _dispatch_continuation_init_slow + 64
1  libdispatch.dylib              0x7fff729a46b0 dispatch_after + 521
2  Ably                           0x10ea88712 artDispatchScheduled + 324
3  Ably                           0x10ea9196a -[ARTEventListener startTimer] + 131
4  Ably                           0x10eab79ee -[ARTRealtimeInternal transition:withErrorInfo:] + 481
5  Ably                           0x10eab7a71 -[ARTRealtimeInternal transitionToDisconnectedOrSuspendedWithError:] + 76
6  Ably                           0x10eabeaa0 -[ARTRealtimeInternal realtimeTransportFailed:withError:] + 807
7  Ably                           0x10ea8f044 -[ARTWebSocketTransport webSocket:didFailWithError:] + 180
8  libdispatch.dylib              0x7fff72990d53 _dispatch_call_block_and_release + 12
9  libdispatch.dylib              0x7fff72991dcf _dispatch_client_callout + 8
10 libdispatch.dylib              0x7fff72998124 _dispatch_lane_serial_drain + 618
11 libdispatch.dylib              0x7fff72998bdc _dispatch_lane_invoke + 388
12 libdispatch.dylib              0x7fff729a1090 _dispatch_workloop_worker_thread + 603
13 libsystem_pthread.dylib        0x7fff72bd260b _pthread_wqthread + 409
14 libsystem_pthread.dylib        0x7fff72bd2405 start_wqthread + 13
```

Has anything like this been reported before? Is there any other info I could try and get which would be useful in debugging?

**Comment by QuintinWillison** [comment]
Thanks for the report, @SpencerCDixon 😁 

I'm not aware of anybody else reporting this yet but I see you are using the latest release so it's clearly a concern!
When you say it's a "regular crash", can you expand on that a little? Any idea of a way to reproduce?

Also, is this blocking you right now?
@ricardopereira should be able to take a look later in the week, if that's soon enough.

**Comment by SpencerCDixon** [comment]
> When you say it's a "regular crash", can you expand on that a little? Any idea of a way to reproduce?

It's our most common crash which is why we're now tracking it down. Probably get it ~20-30 times a week. We haven't gotten many user reports so I imagine it's happening primarily in the background when computers go asleep and wake up. 

No reliable way to reproduce unfortunately :( 

Appears to me like a null pointer deref, but I could be totally off! 

Seems to happen on MBP more than other devices (but we probably also just have way more users using MBPs so hard to say for sure). 

<img width="463" alt="Screen Shot 2020-11-03 at 2 37 35 PM" src="https://user-images.githubusercontent.com/7471018/98032518-207fe880-1de2-11eb-8c89-68e8ceba2a95.png">

> Also, is this blocking you right now?

Not a huge blocker but would be nice to get it resolved soonish. Happy to try any git SHAs in future releases to see if it resolves the issue.

**Comment by QuintinWillison** [comment]
That info does help direct our investigations. I'll discuss with the team. Thanks, @SpencerCDixon. 😁
