### ISSUE TITLE
In last version, connecting to server takes too long time on old devices

### ISSUE THREAD

**Issue by ekoll** [ably/ably-cocoa#1102]
### Which version of the Ably SDK are you using? 
`1.2.3`

### On which platform does the issue happen? 
`iOS12` But not sure its about ios version. It could be about device. I've run into this issue with iPhone 5 and 6. Also tried with iPhone 8 Plus simulator with iOS 12.4, but did not see a problem.

### Are you using Carthage? 
No

### Are you using Cocoapods? 
Yes, `1.10.1`

### Which version of Xcode are you using? 
Xcode 12.4
Build version 12D4e

### What did you do?
I just set my configs and start connection.

### What did you expect to happen?
Connect server successfully

### What happened instead?
Client can connect to server. But on old devices like iPhone5 and iPhone 6 (as I oberve), this process takes about 1-2 minutes.

There is no log between connecting and connected statuses.

I can solve this issue by rolling back to v1.2.2. So this should be about changes that made in last version.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-629) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
Hi @ekoll - we're not aware of an issues and the 1.2.3 changes were focussed and relatively minor, so I certainly wouldn't expect them to have fundamentally changed the connectivity. We would need more information than this to help you debug the issue, so it would help if you could consult [this Guide](https://knowledge.ably.com/guide-information-we-need-to-help-you-diagnose-problems). If there's anything you need to share or discuss that you can't post to this public issue then please do reach out to our support team (you can open a chat window from that page, for example). Thanks.
