### ISSUE TITLE
App Store upload problem - non-public API use

### ISSUE THREAD

**Issue by cibetik** [ably/ably-cocoa#1104]
Hi,  do you experience the same problem as me? I am using Ably in my iOS app and I cannot upload it to App Store since I am getting this error:

ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/Ably.framework/Ably: initWithURLRequest:, readyState, send:, setDelegateDispatchQueue:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.

is this known error? How should I proceed?

Thanks!

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-660) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
Hi @cibetik - we were not aware of this as nobody else has reported submission issues. That is really interesting and apologies for any inconvenience. We'll take a look.

Additional information that would help us is:

- Which version of this SDK are you using?
- How are you integrating the SDK into your project - either:
    - Are you using Carthage? If yes, specify the version (`carthage version`)
    - or, are you using Cocoapods? If yes, specify the version (`pod --version`)

Thanks.

**Comment by cibetik** [comment]
@QuintinWillison thanks for reply!

I am using Carthage 0.37.0 

versions:
- github "ably-forks/SocketRocket" "0.5.2-ably-7"
- github "ably/ably-cocoa" "1.2.3"
- github "ably/delta-codec-cocoa" "1.2.0"

PJ

**Comment by QuintinWillison** [comment]
Hmm, very curious. This particular ITMS complaint seems to be [reported by many](https://www.google.com/search?q=apple+ITMS-90338) but, in the quick read I've had of responses to questions out there, there is little concrete indication of a single solution or even a way to get local build tools to spot this ahead of app submission.

We'll take a closer look and get back to you. Thanks for the report.

**Comment by ricardopereira** [comment]
Hi @cibetik, we believe this is related with a dependency we use called SocketRocket. Could you tell us what's the minimum deployment target of your app? Do you still support iOS 12 and older?

**Comment by QuintinWillison** [comment]
It's worth mentioning that we have https://github.com/ably/ably-cocoa/pull/1090 yet to land (compiles SocketRocket sources within our SDK, rather than via dependency), though that may not fix this either.

From our [internal Slack conversation](https://ably-real-time.slack.com/archives/CSQEKCE81/p1617141170020300), we may need to refactor to use [URLSessionWebSocketTask](https://developer.apple.com/documentation/foundation/urlsessionwebsockettask) - however that class is only available from iOS 13.0 runtime and later.

**Comment by maratal** [comment]
Method names reported by Apple are pretty random, f.e. here - https://developer.apple.com/forums/thread/656894
I think we just have very misleading error message here and renaming will not help. Probably they detect private API call _somewhere_ in the source code and just report topmost method name as a cause. The real question is why not _all_ users report this? WDYT @lukasz-szyszkowski @ben-xD

**Comment by lukasz-szyszkowski** [comment]
That's interesting why it's not reproducible on the Apple side. Is it still happening or it was just a "one-shot"?

**Comment by maratal** [comment]
@cibetik Couldn't you please update us on this issue?

**Comment by QuintinWillison** [comment]
We've not been able to reproduce this and @cibetik has not got back to us with any indication that this is still causing an issue.
