### ISSUE TITLE
Implement RSC7d (Ably-Agent header)

### ISSUE THREAD

**Issue by owenpearson** [ably/ably-cocoa#1111]
see [PR](https://github.com/ably/docs/pull/1034) and [spec point](https://ably-docs.herokuapp.com/client-lib-development-guide/features/#RSC7d) for context.

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-685) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
For this platform I do wonder whether _how_ the client library was built may also be important, given the customer is often building our library from source to integrate into their app. See [this internal conversation](https://ably-real-time.slack.com/archives/CSQEKCE81/p1619606795034000).
