### ISSUE TITLE
Implement RSC15f (successful fallback host)

### ISSUE THREAD

**Issue by ricardopereira** [ably/ably-cocoa#1115]
> ([RSC15f](https://docs.ably.io/client-lib-development-guide/features/#RSC15f)) Once/if a given fallback host succeeds, the client should store that successful fallback host for ClientOptions.fallbackRetryTimeout. Future HTTP requests during that period should use that host. If during this period a qualifying errors occurs on that host, or after fallbackRetryTimeout has expired, it should be un-stored, and the fallback sequence begun again from scratch, starting with the default primary host (rest.ably.io or ClientOptions#restHost) or, in the case of an existing fallback realtime connection as per (RTN17e), with the current fallback realtime host.

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-717) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
@lukasz-szyszkowski  Isn't the issue https://github.com/ably/ably-cocoa/issues/815 is a duplicate of this one?

**Comment by lukasz-szyszkowski** [comment]
Hmmm, it looks like a duplicate. #815 is three years old.
