### ISSUE TITLE
Implement ErrorInfo URLs to help debug issues

### ISSUE THREAD

**Issue by kavalerov** [ably/ably-cocoa#1125]
Related docs: https://ably.com/documentation/realtime/types#error-info

@ben-xD  can you please point to right part of the spec that corresponds to this?

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-914) by [Unito](https://www.unito.io)

**Comment by ben-xD** [comment]
The docs doesn't have anything about URLs (`href`) **except** for Flutter. (for any language selected). The **feature spec** does `href` though, in [TI1](https://docs.ably.io/client-lib-development-guide/features/#TI1) and TI4:

> (TI1) Provides a generic Ably ErrorInfo object that contains Ably code, statusCode (analogous to HTTP status code), message, optional cause, optional href, and optional requestId (RSC7c) attributes

I'm wondering if other libraries actually implement `href`.

**Comment by paddybyers** [comment]
> I'm wondering if other libraries actually implement `href`.

Generally they do, yes.
