### ISSUE TITLE
SDK client should automatically use clientId from the tokenParams or TokenDetails (RSA7b2)

### ISSUE THREAD

**Issue by ben-xD** [ably/ably-cocoa#1126]
I don't think ably-cocoa supports [RSA7b2](https://docs.ably.io/client-lib-development-guide/features/#RSA7b2)

> (RSA7b) Auth#clientId is not null when:
  > (RSA7b2) Token authentication is being used, and the TokenRequest or TokenDetails object, used for authentication, has a clientId value that is not null

If I were to summarize: SDK client should automatically use clientId from the tokenParams or TokenDetails if `clientId` is set to null in clientOptions. I believe this is clearer.

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-919) by [Unito](https://www.unito.io)

**Comment by paddybyers** [comment]
We should then also check that it supports https://docs.ably.io/client-lib-development-guide/features/#RSA7b3. (This is the case that the client is provided with a token, which is implicitly bound to a `clientId`, but the token itself is opaque to the library; the library first learns about the `clientId` after having connected.

**Comment by lawrence-forooghian** [comment]
We do have [automated tests for the `RSA7*` spec points](https://github.com/ably/ably-cocoa/blob/d5741ce8d3bbce0cfda7e91ff5dccc3004f81eb0/Spec/Tests/AuthTests.swift#L1133-L1220), but they don't seem to be testing the value of `Auth#clientId`.

**Comment by maratal** [comment]
> We do have [automated tests for the `RSA7*` spec points](https://github.com/ably/ably-cocoa/blob/d5741ce8d3bbce0cfda7e91ff5dccc3004f81eb0/Spec/Tests/AuthTests.swift#L1133-L1220), but they don't seem to be testing the value of `Auth#clientId`.

BTW feature points `RSA7a2` and `RSA7a3` are absent in the [spec](https://sdk.ably.com/builds/ably/specification/main/features/#RSA7a)

**Comment by lawrence-forooghian** [comment]
Sorry, @maratal, my mistake. I linked to the tests for `RSA7a*` by accident. The relevant ones here are the ones for [`RSA7b*`](https://github.com/ably/ably-cocoa/blob/d5741ce8d3bbce0cfda7e91ff5dccc3004f81eb0/Spec/Tests/AuthTests.swift#L1275-L1351). At a glance, it looks like they're testing the right thing, you might need to look at https://github.com/ably/ably-asset-tracking-swift/issues/401 and run the failing tests mentioned there to investigate further.

But good catch re the extra tests. I created https://github.com/ably/ably-cocoa/issues/1507 for that.

**Comment by maratal** [comment]
This was finally solved here https://github.com/ably/ably-cocoa/pull/1517

**Comment by lawrence-forooghian** [comment]
@maratal I don't think that this was in #1517 – that PR was for enforcing RTP8j. I'm going to reopen this one. Can you please confirm whether or not there is any work we need to do on this?

**Comment by maratal** [comment]
I think that the current implementation 
```
- (NSString *)clientId_nosync {
    if (_protocolClientId) {
        return _protocolClientId;
    }
    else if (self.tokenDetails && self.tokenDetails.clientId) {
        return self.tokenDetails.clientId;
    }
    else {
        return self.options.clientId;
    }
}
```
reflects specs better, than the one proposed by Ben, which implies to check for `options.clientId` first. And the phrase "Auth#clientId is not null when ... token authentication is being used, and the TokenRequest or TokenDetails object ... has a clientId value that is not null" doesn't mean that. @lawrence-forooghian

**Comment by lawrence-forooghian** [comment]
I agree that the current implementation looks mainly fine, @maratal. I don't understand the motivation for the original issue. Will close this.
