### ISSUE TITLE
Remove `ULID` dependency (replace usage with `NSUUID`)

### ISSUE THREAD

**Issue by ben-xD** [ably/ably-cocoa#1127]
I propose we remove `[[ULID new] ulidString]` (last usage of [ULID](https://github.com/whitesmith/ulid)), which is in [`ARTLocalDevice.m`](https://github.com/ably/ably-cocoa/blob/main/Source/ARTLocalDevice.m).

@ricardopereira, I wanted to see what your thoughts are about this. There might be a good reason its being used instead of the built-in `NSString *randomId = [NSUUID new].UUIDString;`?

Benefits:
- Remove uncommonly used dependency (ULID) and just use built-in functionality (small increase in portability, security, usability, readability, maintainability, etc).

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-923) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
See also: https://github.com/ably/ably-cocoa/issues/949

**Comment by ricardopereira** [comment]
At that time, `ULID` was the to-go solution defined in the spec. As far as I know, it is safe to use `NSUUID`. Toni can give you more details on that.

**Comment by QuintinWillison** [comment]
Thanks, @ricardopereira.

@tcard has since responded [internally](https://ably-real-time.slack.com/archives/CSQEKCE81/p1623078164135600?thread_ts=1623073211.125700&cid=CSQEKCE81) with:

> I'm the person who originally introduced ULID for push. there's no need for it, UUID4 is fine
