### ISSUE TITLE
Fix temporarily ignored presence tests

### ISSUE THREAD

**Issue by ben-xD** [ably/ably-cocoa#1140]
Tests related to presence were disabled to get open PRs merged in. We should fix these broken tests asap. The tests disabled can be found in https://github.com/ably/ably-cocoa/pull/1134.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-953) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
[Fixed](https://github.com/ably/ably-cocoa/issues/1848)
