### ISSUE TITLE
Add Ably-cocoa swift package to Swift Package Index

### ISSUE THREAD

**Issue by ben-xD** [ably/ably-cocoa#1141]
Users can search for Swift Packages on https://swiftpackageindex.com/

To add `ably-cocoa` to this list, you have to add ably-cocoa's github repo to this file: https://github.com/SwiftPackageIndex/PackageList/blob/main/packages.json or follow [this](https://swiftpackageindex.com/add-a-package) guide.

We should do this once we release SPM support

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-957) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
https://github.com/SwiftPackageIndex/PackageList/pull/1289

**Comment by ben-xD** [comment]
It's now available on SPI: https://swiftpackageindex.com/ably/ably-cocoa

Nice
