### ISSUE TITLE
Conform ReadMe and create Contributing Document

### ISSUE THREAD

**Issue by lukasz-szyszkowski** [ably/ably-cocoa#1144]
There should be created CONTRIBUTING.md file for development purpose. One thing that needs to be written down to this file is SPM configuration, especially headers symlinks and where to place them in file structure (and why).

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-962) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
In https://github.com/ably/ably-common/pull/88 we have defined template layouts for `README.md` and `CONTRIBUTING.md`, hosted [here](https://github.com/ably/ably-common/tree/main/templates).

Those documents need conforming in this repository, which necessitates the forking of the current readme content to produce the contributing guide.

This is also a good opportunity to review what's currently here.

**Comment by maratal** [comment]
This issue depends on https://github.com/ably/ably-cocoa/issues/1070
The docs should be updated _after_ carthage removal.

**Comment by jamienewcomb** [comment]
Do we have to wait for #1070 and #1137 to be completed here? can we not make incremental improvements now and then update again after those issues have been dealt with?

**Comment by maratal** [comment]
I would wait, Carthage is a big chunk of text for these docs, @lukasz-szyszkowski WDYT?

**Comment by lukasz-szyszkowski** [comment]
Firstly we have to be sure if we'll remove Carthage support and if yes, when? @QuintinWillison @AndyNicks 
If it won't happen in, let's say, the next 1-2 more months, I recommend not waiting for #1070 and #1137

**Comment by QuintinWillison** [comment]
@maratal I understanding your point of view, but it sounds like the effort required to capture and document (in the conformed way) what we have right now is significantly less than the time required to ditch Carthage. I think it is worth capturing the current state of things. Once the docs are then conformed / reshaped, it'll be easier to then replace Carthage as a later increment.
