### ISSUE TITLE
Allow users to set String APNs device token (currently only NSData is supported)

### ISSUE THREAD

**Issue by ben-xD** [ably/ably-cocoa#1174]
Currently, when a new APNs device token is received by the device, the user can just pass the NSData received by the device by using `ARTPush:didRegisterForRemoteNotificationsWithDeviceToken:rest:` (or `realtime:`)

I wanted to change the APNs token manually to check if APNs device token updates succeed in Ably-cocoa. Unfortunately, creating an NSData which is a correct representation of APNs device token is quite involved. (Going from NSData is NSString to is well documented by Apple, but the reverse is not). I faced this issue when testing if changing the APNs token would succeed in Ably-cocoa, since APNs device tokens do not change very often.

It would also be a nicer API for users to provide Strings. It would be a great convenience to me, and also other developers who are debugging/ testing if device token updates are successful. Additionally, if the user uses a library which provides a String device token, they should still be able to pass that to Ably.

Internally, ably-cocoa already converts this NSData into an NSString, I am simply asking for there to be a way to bypass the internal conversion, and just let the user give the String instead of Ably creating it.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1171) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
As I understand it, this issue is saying that we should provide a method that allows a user to provide a hex representation of the data. I don't see how this is universally useful.

> Additionally, if the user uses a library which provides a String device token, they should still be able to pass that to Ably.

There isn't such a thing as a "String device token". The device token is an `NSData`. To represent it as a string requires a choice of representation. Hex is only one possible representation.
