### ISSUE TITLE
Push device deregistration does not clear/ reset device details 

### ISSUE THREAD

**Issue by ben-xD** [ably/ably-cocoa#1177]
This is quite low priority, but here it is:

As per [RSH3g2a](https://docs.ably.io/client-lib-development-guide/features/#RSH3g2a):
> On On event `Deregistered`, Clears all local DeviceDetails.

Unfortunately, ably-cocoa does not clear local device details.

In Java, this can be seen by:
https://github.com/ably/ably-java/blob/2b8e3c7e65ee7109f225cad115df38d61869fc3f/android/src/main/java/io/ably/lib/push/ActivationStateMachine.java#L483

Ably-cocoa does not even have a method to reset the device details, and so is definitely not calling this. 

This can be seen functionality in the Ably flutter app, in the following recording:

https://user-images.githubusercontent.com/24711048/133272418-87678115-c3be-49b4-a6c6-55ac8d23d112.mov

* On the left is Ably-flutter running on Android. I activate and deactivate, and the device details clearly changes.
* On the right is Ably-flutter running on iOS, and activation/ deactivation doesn't change the device details.
* iOS :bug:: When deactivating the device, the LocalDevice should be **reset**. It should not keep the same local device information. This means the deviceId and ~APNs device token (registration tokens on Android)~ could be **different**. The APNs device token on iOS and FCM registration token on Android remains the same. A different APNs device token might be possible on iOS, potentially by calling [`unregisterForRemoteNotifications`](https://developer.apple.com/documentation/uikit/uiapplication/1623093-unregisterforremotenotifications). You could test this.

Note on the flutter app: The app is just calling the device method to show the device information.

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-1181) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
Isn't `[local setAndPersistIdentityTokenDetails:nil];` in `ARTPushActivationStateWaitingForDeregistration:transition` is for?

**Comment by ben-xD** [comment]
I'm not sure what you're saying @maratal, can you clarify? 🙂

**Comment by maratal** [comment]
@ben-xD couldn't you play with PR branch? [push-interactive-app](git@github.com:ably/push-example-ios.git) is so lame, it requires a lot of work to fix it (I'm into it now). Thanks.

**Comment by ben-xD** [comment]
I initially didn't understand Marat's comments but he clarified it with me. 

> Isn't [local setAndPersistIdentityTokenDetails:nil]; in ARTPushActivationStateWaitingForDeregistration:transition is for?

He said this is an outdated comment and not relevant anymore.

> @ben-xD couldn't you play with PR branch? push-interactive-app is so lame, it requires a lot of work to fix it (I'm into it now). Thanks.

He wants me to test it in Ably-Flutter because https://github.com/ably/push-example-ios is not well written, and we definitely agree it needs significant improvements.

**Comment by maratal** [comment]
Reopening due to https://github.com/ably/ably-cocoa/pull/1272

**Comment by maratal** [comment]
Partially fixed by #1832
