### ISSUE TITLE
App crash and dyld error message (AblyDeltaCodec cannot be loaded, image not found) when using XCFrameworks on macOS app.

### ISSUE THREAD

**Issue by saragiro** [ably/ably-cocoa#1183]
A customer has reported that they’re getting a dyld error (AblyDeltaCodec cannot be loaded, image not found.) when attempting to use XCFrameworks instead of Carthage, whilst attempting to follow the instructions in

https://github.com/ably/ably-cocoa to build their macOS app.

The application runs fine from Xcode but upon installing the app on the test machine, the app crashes with dyld error message because AblyDeltaCodec cannot be loaded, image not found.

Steps followed prior to the error & crash were:

1-Changed Carthage update to include --use-xcframeworks
2-Removed the old framework references from the project
3-Dragged the three XCFrameworks from the Carthage build folder into the project
4-Confirmed that all three are in the Frameworks, Libraries and Embedded Content list on the General tab and that they have Do Not Embed selected
5-Confirmed all three are in the Link Binary with Libraries list in Build Phases

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-1256) by [Unito](https://www.unito.io)

**Comment by saragiro** [comment]
A customer has reported that they’re getting a dyld error (AblyDeltaCodec cannot be loaded, image not found.) when attempting to use XCFrameworks instead of Carthage, whilst attempting to follow the instructions in

https://github.com/ably/ably-cocoa to build their macOS app.

The application runs fine from Xcode but upon installing the app on the test machine, the app crashes with dyld error message because AblyDeltaCodec cannot be loaded, image not found.

**Steps followed prior to the error & crash were:**

1) Changed Carthage update to include ``--use-xcframeworks``
2) Removed the old framework references from the project
3) Dragged the three XCFrameworks from the Carthage build folder into the project
4) Confirmed that all three are in the _Frameworks, Libraries and Embedded Content_ list on the _General_ tab and that they have _Do Not Embed_ selected
5) Confirmed all three are in the _Link Binary with Libraries_ list in _Build Phases_

**Comment by lawrence-forooghian** [comment]
@saragiro told me that we provided the customer with some additional instructions, which by the sounds of it involved running some additional shell script that I don't think is documented (at least that's what I understand from the [original internal Slack thread](https://ably-real-time.slack.com/archives/CSQEKCE81/p1632827332111400)), and that the customer told us that this solved their issue. Sounds like we should still check our documentation and whether it's sufficient.
