### ISSUE TITLE
Add Swift Package Manager badges to README.md

### ISSUE THREAD

**Issue by lukasz-szyszkowski** [ably/ably-cocoa#1204]
Add info badges about **Swift Compatibility** and **Platform Compatibility** to `README.md`

https://swiftpackageindex.com/ably/ably-cocoa/information-for-package-maintainers

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1343) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
Sounds like a good idea to me. Thanks.

**Comment by smhk** [comment]
Guys, no iPhone project and no library or platform now uses "cocoa pods" or "carthage".  Your quick start documentation on the ably homepage still talks about "cocoa pods" and does not even mention SPM.  (I wasted 15 minutes trying to find out if you actually have an SPM.)

It's not 1950 - would it be wise to drop all mention of "pods" and "carthage" certainly from the main web site doco and perhaps from git?

The situation is very confusing and "out of date". My colleague sitting next to me glanced at this, said "what are they doing monkeying with pods" and he moved on and will never try ably.

Maybe you have few apple users, IDK

Again in short it was frustrating to see historic systems mentione on the main "quick start" on the web page, and a waste of 15 minutes.  Anyway hope it helps
