### ISSUE TITLE
Missing properties in ARTClientOptions

### ISSUE THREAD

**Issue by ikbalkaya** [ably/ably-cocoa#1260]
Captured in following issue 
https://github.com/ably/ably-flutter/issues/14

There are some properties missing  in ARTClientOptions. I checked ones that were not relevant anymore. The remaining properties
* `useTokenAuth`
* `realtimeRequestTimeout`
* `fallbackRetryTimeout`
* `asyncHttpThreadpoolSize`

For details of the properties please see linked issue.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1451) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
Research references:

* `useTokenAuth` - that's in [`ARTAuthOptions`](https://docs.ably.io/client-lib-development-guide/features/#TO3j)
* `realtimeRequestTimeout` - that's in `ARTDefault`, described in docs as a [part of defaults](https://docs.ably.io/client-lib-development-guide/features/#DF1b), not options
* `fallbackRetryTimeout` - also in `ARTDefault`, but should go in client options [according to the docs](https://docs.ably.io/client-lib-development-guide/features/#TO3l10)
* `asyncHttpThreadpoolSize` - this is something that was removed from docs presumably (https://docs.ably.io/client-lib-development-guide/features contains nothing like that at least)

So, for all mentioned properties only `fallbackRetryTimeout` requires implementation in the `ARTClientOptions`
