### ISSUE TITLE
Missing properties in ARTErrorInfo

### ISSUE THREAD

**Issue by ikbalkaya** [ably/ably-cocoa#1261]
Captured in following Flutter issue
https://github.com/ably/ably-flutter/issues/14

Following properties are missing from ARTErrorInfo class

* `code`
* `cause`

Please see linked issue for details of each property

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1452) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
* `code` - this one inherited from `NSError`
* `cause` - I guess it's a `reason` in `ARTErrorInfo`, unless docs give no room for the platform specific implementation it can be kept as is. WDYT @ikbalkaya @lawrence-forooghian @lukasz-szyszkowski @QuintinWillison

**Comment by QuintinWillison** [comment]
From [TI1](https://docs.ably.com/client-lib-development-guide/features/#TI1) and [the IDL](https://docs.ably.com/client-lib-development-guide/features/#idl), we can see that `cause` is an optional `ErrorInfo` instance. [The `reason` property on `ARTErrorInfo`](https://github.com/ably/ably-cocoa/blob/6b3c9beb46f9bb373f946d660e6d70d7dbc40661/Source/ARTStatus.h#L194) is a string, so not the same thing.

Therefore, perhaps, `cause` is more aligned with one, other or both of:

- [the `NSUnderlyingErrorKey`](https://developer.apple.com/documentation/foundation/nsunderlyingerrorkey?language=objc), used for [`NSError`'s `userInfo` property](https://developer.apple.com/documentation/foundation/nserror/1411580-userinfo?language=objc)
- [`NSError`'s `underlyingErrors` property](https://developer.apple.com/documentation/foundation/nserror/3738169-underlyingerrors?language=objc)

Perhaps one of the corners of Apple's APIs that could best be described as a bit of a 'hot mess' (not unlike our own `ErrorInfo` 'concept', but I digress 🙄)... so, I think to fix this issue:

1. We need to add a `cause` issue to `ARTErrorInfo`, of type `ARTErrorInfo`
2. Work out an appropriate algorithm for populating it... do we have any existing examples of where it might have revealed something interesting that we can model on?

**Comment by maratal** [comment]
>...and [the IDL](https://docs.ably.com/client-lib-development-guide/features/#idl), we can see that cause is an optional ErrorInfo instance.

You are right, my bad.

**Comment by maratal** [comment]
> Work out an appropriate algorithm for populating it...

From the docs to `NSUnderlyingErrorKey`:
> The corresponding value is an error that was encountered in an underlying implementation and _caused_ the error that the receiver represents to occur.

Seems like the `NSUnderlyingErrorKey` is  a perfect match for `cause` property.
