### ISSUE TITLE
According to spec, the SDK should be responsible for calling `-[UIApplication registerForRemoteNotifications]`, not the user

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-cocoa#1271]
## Description

[`RSH3a2d`](https://ably.com/documentation/client-lib-development-guide/features#RSH3a2d) says:

> On event `CalledActivate` … If the local device does not have the necessary push details, it initiates a request to the underlying platform (or otherwise generates them).

I believe that on iOS, to "initiate a request to the underlying platform" is to call `-[UIApplication registerForRemoteNotifications]`. However:

- This SDK never calls that method.
- We have various pieces of documentation and example code that suggest that a user of the library needs to call this method on app startup:
  - [Documentation: "Push Notifications - Device activation and subscription"](https://ably.com/documentation/general/push/activate-subscribe):
     > In `UIApplicationDelegate#didFinishLaunchingWithOptions`, call `UIApplication.shared.registerForRemoteNotifications`.

    But then later on in the same article (section 2.1), it says that calling `activate` will:

    > Activate the device for push notifications with the underlying OS or platform and obtain a unique identifier for the device as a push recipient
  
  - [iOS push notifications tutorial, step 6](https://ably.com/tutorials/ios-push-notifications#step6-register-device-for-push) demonstrates calling this method on app startup.
  - Our [push-example-ios example app](https://github.com/ably/push-example-ios) copies this pattern, [calling the method on app startup](https://github.com/ably/push-example-ios/blob/49e4f6532927979af34507f16138a6a278330dba/push-interactive-app/AppDelegate.swift#L43). 

## Next steps

- Confirm whether we believe the behaviour described by the spec to be the right one
- If so, implement it in the library and remove the call to this method from our documentation / example code (confirm that existing code that does call this method will still work fine).

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1503) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
Here is related issue https://github.com/ably/ably-cocoa/issues/1159
