### ISSUE TITLE
Put all check jobs for each platform in a different GH workflow

### ISSUE THREAD

**Issue by maratal** [ably/ably-cocoa#1273]
Now in case of one workflow job failure it requires to re-run all jobs in this workflow. It takes a few hours before needed "combination" of all of them being green will pop up. We should de-couple it to have an ability to re-run only the ones that failed.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1507) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
@maratal and I have discussed this via Slack. I've also been thinking the same for a while, across a few of our SDKs.

- needs to align with our new(er) guidance for workflows: https://github.com/ably/engineering/blob/main/sdk/github.md#workflows
- perhaps helped by this feature, but this theory is not validated yet so needs research: https://docs.github.com/en/actions/using-workflows/reusing-workflows
