### ISSUE TITLE
Replace real requests with recorded mocks

### ISSUE THREAD

**Issue by maratal** [ably/ably-cocoa#1278]
Currently test suite uses real requests (except a few test cases) to ably infrastructure. It significantly increases tests run session duration and failure rate which prevents PRs to be merged into main branch. This issue is for discussion possible solutions to this problem. As a pretty obvious first step would be to record real request/response pairs and then replay them.

┆Issue is synchronized with this [Jira Research](https://ably.atlassian.net/browse/SDK-1523) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
Useful links:
https://github.com/venmo/DVR
https://github.com/dstnbrkr/VCRURLConnection
https://wiremock.org
https://www.mock-server.com

**Comment by maratal** [comment]
Apart from 10 tests that I've switched back to `ARTHttp` (from MockHTTP, which doesn't make any request at all - branch feature/1278-recorded-mocks) there are only 19 failed tests left (out of 904!):

<img width="700" alt="Screenshot 2022-02-01 at 17 09 49" src="https://user-images.githubusercontent.com/45491869/152006749-99140c36-4bd0-457a-953c-f8c03a3c5f2d.png">

So far so good, tests run should speed up significantly even without recording/replaying real requests for these few tests which require them.

**Comment by lawrence-forooghian** [comment]
Hey @maratal, we have a wider story for stabilising our tests (#1279), which I'll be working on after I've finished what I'm currently working on. I'll take a closer look at the work you've done here as part of that, but I think we first need to get a better understanding of what's causing the current instability, so that's where I'll be starting.

**Comment by maratal** [comment]
Closing this as not relevant at the current stage of testing functionality.
