### ISSUE TITLE
Failing test: test__001__Presence__should_complete_the_SYNC_operation_when_the_connection_is_disconnected_unexpectedly

### ISSUE THREAD

**Issue by maratal** [ably/ably-cocoa#1286]
It always fails with "Should send one SYNC protocol message", because `transport.protocolMessagesSent` is an empty array.

```
let syncSentProtocolMessages = transport.protocolMessagesSent.filter { $0.action == .sync }
guard let syncSentMessage = syncSentProtocolMessages.last, syncSentProtocolMessages.count == 1 else {
   fail("Should send one SYNC protocol message"); return
}
```

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-1566) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
Hey @maratal - could you please expand on what you mean by "it always fails"? I assume you don't mean it fails every time we run it, else we'd never have a green CI run.

**Comment by maratal** [comment]
@lawrence-forooghian it's marked as "skipped"

**Comment by lawrence-forooghian** [comment]
Thanks Marat – I would assume it's skipped for this reason. Thanks for making a GitHub issue for it.
