### ISSUE TITLE
Library user experiencing issue with received integers gaining a fractional component

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-cocoa#1326]
## Description of the issue

We recently talked to a library user who has experienced issues that potentially relate to our SDK's handling of numerical values in message data.

The issue is that they published (exact mechanism unclear, see below) a message whose data contained a numerical value with no fractional component, but upon receiving this published message in the iOS SDK and converting it to a `Double` and then a `Decimal`, the number gained a fractional component. (I do not know _why_ the user was trying to first convert the number to a `Double` before converting to a `Decimal`, instead of converting to an `Int` and then a `Decimal`. You can see the difference this makes in my examples below.)

I don't know whether in this user's use case, the data was published using JSON or MessagePack (this is relevant because the two formats support different ways of representing numbers, and also we use different libraries to parse them). 

## My attempts to reproduce

In both the examples, the issue is the line `integerExampleAsDoubleAsDecimal is 1756699.0000000002048`.

### Swift code

```swift
import Ably

let client = ARTRealtime(key: "<API key>")

let channel = client.channels.get("myChannel")

channel.subscribe { message in
    print("Received message \(message), with data \(String(describing: message.data))")
    
    let data = message.data as! [String: Any]
    let integerExample = data["integerExample"]!
    
    print("integerExample is \(integerExample), type \(type(of: integerExample))")
    
    let integerExampleAsDouble = integerExample as? Double
    let integerExampleAsInt = integerExample as? Int
    let integerExampleAsDecimal = integerExample as? Decimal
    
    if let integerExampleAsDouble = integerExampleAsDouble {
        print("integerExampleAsDouble is \(integerExampleAsDouble), type \(type(of: integerExampleAsDouble))")
        let integerExampleAsDoubleAsDecimal = Decimal(integerExampleAsDouble)
        print("integerExampleAsDoubleAsDecimal is \(integerExampleAsDoubleAsDecimal)")
    }
    else {
        print("integerExampleAsDouble is nil")
    }
    
    if let integerExampleAsInt = integerExampleAsInt {
        print("integerExampleAsInt is \(integerExampleAsInt)), type \(type(of: integerExampleAsInt))")
        let integerExampleAsIntAsDecimal = Decimal(integerExampleAsInt)
        print("integerExampleAsIntAsDecimal is \(integerExampleAsIntAsDecimal)")
    }
    else {
        print("integerExampleAsInt is nil")
    }

    if let integerExampleAsDecimal = integerExampleAsDecimal {
        print("integerExampleAsDecimal is \(integerExampleAsDecimal)), type \(type(of: integerExampleAsDecimal))")
    }
    else {
        print("integerExampleAsDecimal is nil")
    }

}

print("Subscribed to \(channel)")
RunLoop.main.run()
```

### Publishing using JSON

```bash
curl -X POST https://rest.ably.io/channels/myChannel/messages \
 -u "<API key>" \
 -H "Content-Type: application/json" \
 --data '{ "name": "publish", "data": {"integerExample": 1756699} }'
```

This gives the following output:

```
integerExample is 1756699, type __NSCFNumber
integerExampleAsDouble is 1756699.0, type Double
integerExampleAsDoubleAsDecimal is 1756699.0000000002048
integerExampleAsInt is 1756699), type Int
integerExampleAsIntAsDecimal is 1756699
integerExampleAsDecimal is nil
```

### Publishing using MessagePack

```bash
echo '{ "name": "publish", "data": {"integerExample": 1756699} }' | json2msgpack | curl -X POST https://rest.ably.io/channels/myChannel/messages \
 -u "<API key>" \
 -H "Content-Type: application/x-msgpack" \
 --data-binary @-
```

(This serialises the `integerExample` value as a MessagePack `uint32`.)

This gives the following output (same as the JSON example):

```
integerExample is 1756699, type __NSCFNumber
integerExampleAsDouble is 1756699.0, type Double
integerExampleAsDoubleAsDecimal is 1756699.0000000002048
integerExampleAsInt is 1756699), type Int
integerExampleAsIntAsDecimal is 1756699
integerExampleAsDecimal is nil
```

### Further information

[Internal thread (Ably Slack)](https://ably-real-time.slack.com/archives/CSQEKCE81/p1648814282841749?thread_ts=1647355116.310079&cid=CSQEKCE81) - contains further information about the user’s original code

### Other thoughts by the user

We discussed the possibility of exposing the raw message `data` received from Ably (as an `NSData` for example) and allowing the the user to deserialise the message themselves if not satisfied with our deserialisation logic. It would be nice if there was a way to avoid pushing the the complexity of handling multiple serialization formats (i.e. JSON or MessagePack) onto the library user. The user suggested that we could consider exposing an interface on the library that allows the user to pass a `Decodable` type to the library. This would then allow the user to express, in that type, whether they expected certain types to be an integer.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1722) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
Related PR https://github.com/ably/ably-cocoa/pull/1397

**Comment by maratal** [comment]
Related PR https://github.com/ably/ably-cocoa/pull/1405

**Comment by lawrence-forooghian** [comment]
As [discussed](https://github.com/ably/ably-cocoa/pull/1405#discussion_r871417903) in #1405, we're going to address this by giving library users access to the raw JSON data. @maratal has created https://github.com/ably/docs/issues/1425, and we (iOS team) will need to make a PR for the suggested feature spec change before we can progress on this.
