### ISSUE TITLE
Re-enable presence tests that were disabled in #1134

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-cocoa#1408]
┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4366) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
Related issue - https://github.com/ably/ably-cocoa/issues/1876

**Comment by maratal** [comment]
Solved in https://github.com/ably/ably-cocoa/pull/1886
