### ISSUE TITLE
Crash in [ARTSRProxyConnect _failWithError]

### ISSUE THREAD

**Issue by TankKuo** [ably/ably-cocoa#1437]
{panel:bgColor=#deebff}

#### HubSpot linked tickets:
* [ENT - 17Media - Crash Log (Ticket ID: 916965781)](https://app.hubspot.com/contacts/6939709/ticket/916965781)

~_(please, do not edit or duplicate in description)_~
{panel}

### Which version of the Ably SDK are you using? 
1.2.10

### On which platform does the issue happen? 
iOS 14 ~ 15.1

### Are you using Cocoapods? 
If yes, specify the version (`pod 'Ably', '1.2.10'`)

### Which version of Xcode are you using? 
({{ 13.2.1 (13C100)}})

The problem is that I cannot reproduce it.

> Crashed: io.ably.socketrocket.NetworkThread
> 0  libobjc.A.dylib                0x21e0 objc_msgSend + 32
> 1  Story17                        0x1534880 -[ARTSRProxyConnect _failWithError:] + 140 (ARTSRProxyConnect.m:140)
> 2  Story17                        0x1535894 -[ARTSRProxyConnect stream:handleEvent:] + 362 (ARTSRProxyConnect.m:362)
> 3  CoreFoundation                 0xc080c _signalEventSync + 216
> 4  CoreFoundation                 0xbfccc _cfstream_shared_signalEventSync + 392
> 5  CoreFoundation                 0xa3990 **CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION**

* 28
> 6  CoreFoundation                 0xa388c __CFRunLoopDoSource0 + 208
> 7  CoreFoundation                 0xa2b90 __CFRunLoopDoSources0 + 268
> 8  CoreFoundation                 0x9cb70 __CFRunLoopRun + 820
> 9  CoreFoundation                 0x9c308 CFRunLoopRunSpecific + 600
> 10 Foundation                     0x8d8c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 232
> 11 Story17                        0x15363cc -[ARTSRRunLoopThread main] + 70 (ARTSRRunLoopThread.m:70)
> 12 Foundation                     0x17a30c **NSThread__start** + 864
> 13 libsystem_pthread.dylib        0x1bfc _pthread_start + 320
> 14 libsystem_pthread.dylib        0xa758 thread_start + 8
>

**Comment by jamienewcomb** [comment]
Is this still an issue?
