### ISSUE TITLE
Make docs workflow run for all tags

### ISSUE THREAD

**Issue by maratal** [ably/ably-cocoa#1440]
After https://github.com/ably/sdk-upload-action/pull/40 is merged and released, we'll want to make this workflow run for all tags, too, so that we're permanently saving documentation for each release.

```yaml
tags:
    "*"
```

But you can do it as a separate PR later.

_Originally posted by @lawrence-forooghian in https://github.com/ably/ably-cocoa/pull/1428#discussion_r911446901_

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-2383) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
@maratal this can be done now
