### ISSUE TITLE
Investigate whether `plugins` needed in ably-cocoa

### ISSUE THREAD

**Issue by maratal** [ably/ably-cocoa#1462]
https://docs.ably.io/client-lib-development-guide/features/#TO3o

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2544) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
We do not need plugins in this SDK. They were added to the features spec, under [`TO3o`](https://sdk.ably.com/builds/ably/specification/main/features/#TO3o), for the benefit of the JS SDK allowing [VCDiff delta subscription streaming codec](https://github.com/ably/ably-js#subscribing-to-a-channel-with-deltas) to be optional (for those wishing to save on runtime size when not using delta streaming).
