### ISSUE TITLE
[ably-cocoa] Implement no-connection-serial

### ISSUE THREAD

**Issue by jamienewcomb** [ably/ably-cocoa#1494]
Implement the changes listed in https://github.com/ably/specification/pull/88
Reference impl -> https://github.com/ably/ably-js/pull/1045

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4422) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
Jira issue https://ably.atlassian.net/browse/SDK-2636
