### ISSUE TITLE
Channel state changes should not depend on queueMessages

### ISSUE THREAD

**Issue by ikbalkaya** [ably/ably-cocoa#1508]
Context : [Internal slack message](https://ably-real-time.slack.com/archives/C02P7F81DPS/p1666195419198959?thread_ts=1666194178.410779&cid=C02P7F81DPS)
ably-cocoa seems to use `queueMessages` when making state changes on channels. @SimonWoolf pointed out that this flag is irrelevant to channel state changes. The code should be fixed so that there is no check/dependency with  `queueMessages` when channel states change occur.

**Comment by SimonWoolf** [comment]
(I reckon someone saw https://github.com/ably/ably-js/blob/9e79da330a40a868872b6dc4352311d2f2ea1323/src/common/lib/transport/connectionmanager.ts#L1542 in ably-js and misread it as 'this should open happen if event queueing is enabled'. But the ably-js line isn't checking the client option, only the fixed property of the state, it's just a shorthand for 'if state is closed or closing or failed')

**Comment by maratal** [comment]
[Fixed](https://github.com/ably/ably-cocoa/pull/1941)
