### ISSUE TITLE
Xcode 14 Thread Performance Checker warns of a priority inversion from SocketRocket code

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-cocoa#1516]
When running the `PublisherExampleSwiftUI` in https://github.com/ably/ably-asset-tracking-swift (as of commit `3fbec7e`), I get the following warning at runtime from Xcode 14’s [Thread Performance Checker](https://developer.apple.com/documentation/xcode/diagnosing-performance-issues-early#Diagnose-and-resolve-priority-inversions):

```
/Users/lawrence/Library/Developer/Xcode/DerivedData/AblyAssetTracking-gccmfrnumxgxjwcajhzjwbuctlhp/SourcePackages/checkouts/ably-cocoa/SocketRocket/SocketRocket/Internal/RunLoop/ARTSRRunLoopThread.m:79: warning run: Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_DEFAULT. Investigate ways to avoid priority inversions
```

Here's a video of it happening:

https://user-images.githubusercontent.com/53756884/198249366-f83b4182-7dc2-4148-ba7e-75105520ec8f.mov

We should understand and resolve this issue as it probably affects our customers too.

**Comment by papipons** [comment]
Good day!
Any updates on this?
