### ISSUE TITLE
Make sure we can build the library and run the tests using Xcode 14

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-cocoa#1523]
## Motivation

We need to be able to develop the SDK using Xcode 14, since macOS 13 does not run earlier Xcode versions. This means that new developers who are already on macOS 13, or existing developers who perhaps upgraded too hastily (yes, it's me), are unable to develop the library.

## Terminology

Here, I'm using "Xcode 14" to mean "Xcode 14.something".

## Requirements

1. Fix all issues that prevent us from building the SDK and running the tests using Xcode 14. So far, I've identified these ones, but there might be more:
   - https://github.com/ably/ably-cocoa/issues/1511
   - https://github.com/ably/ably-cocoa/issues/1521
   - https://github.com/ably/ably-cocoa/issues/1522
2. Switch CI to build using Xcode 14.

**Comment by maratal** [comment]
Tests are already using Xcode 14.2, so #1511 doesn't prevent them from doing it. Do we still need two issues (this and #1511)? @lawrence-forooghian

**Comment by lawrence-forooghian** [comment]
I think we can close this one now.
