### ISSUE TITLE
Ably `agents` client option is implemented incorrectly

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-cocoa#1525]
As observed in https://github.com/ably/ably-asset-tracking-common/pull/66#issuecomment-1309993388.

Under this issue:

1. Remove the `addAgent:version` method from `ARTClientOptions`
2. Refactor the `agents` method from `ARTClientOptions` to make it a property, akin to `transportParams`
3. Release as a breaking change in a `1.2` series `patch` release, which is ok per [our guidance around adoption of SemVer](https://github.com/ably/engineering/blob/main/sdk/versioning.md#semantic-versioning)

At that point we can update Ably SDK implementations to use this new implementation.

**Comment by lawrence-forooghian** [comment]
@QuintinWillison I'm not sure I understand how the linked versioning guidance says that we can release this as a breaking change in `1.2`. Here's what it says (emphasis mine):

> Up until that point, SDKs should continue to evolve **in a non-breaking manner** with `patch` releases on their `1.2` series - that is, those `patch` releases will continue to attract changes that are `minor` in nature, according to semantic versioning

Isn't that saying that we _can't_ release a breaking change on 1.2?

**Comment by lawrence-forooghian** [comment]
@QuintinWillison Having thought about this a bit more, I think that perhaps the existing [`addAgent:version:`](https://github.com/ably/ably-cocoa/blob/76733cdcc81cac51f8fab19a99fa7442caa39b54/Source/ARTClientOptions.h#L204) is the best way to translate [RSC7d6](https://sdk.ably.com/builds/ably/specification/main/features/#RSC7d6)’s `agents` property to Objective-C. If we were to represent `agents` as an `NSDictionary` mapping agent names to versions, then we'd have to deal with the fact that `NSDictionary` can’t store `nil` values, so we’d have to use `NSNull` (a bit messy) and we’d have to find a way to represent in the method’s signature that it can accept `NSString` or `NSNull` (also a bit messy). The `addAgent:version:` API sidesteps these issues.

In terms of API, the only actual difference between what we have and what the feature spec suggests is that there’s currently no API on `ARTClientOptions` to:

- remove a custom agent from the list
- query the custom agents that are in the the list

but I’m not sure they’re particularly important things to have.

So my suggestion would be that we keep the existing `addAgent:version:` method. What do you think?

**Comment by QuintinWillison** [comment]
I see what you mean around messiness of using `NSNull`.

However, I am still keen to conform APIs across libraries where possible. And I think there is an argument that allowing the outer layer to construct its dictionary in its own way (could be deserialised from JSON, could be dictionary-literal, etc..) is more consistent with its setting (especially looking at `transportParams`).

It's fairly obvious from the spec ([RSC7d1](https://sdk.ably.com/builds/ably/specification/main/features/#RSC7d1) and [RSC7d4](https://sdk.ably.com/builds/ably/specification/main/features/#RSC7d4)) that we don't support empty/zero-length values for `version`. So, I think we could take one of two approaches...

Either:

1. Provide a static constant `NSString` value, being of zero-length, for 'no version' - which we ask developers to supply as the `version` value for the case that they're supplying a product component with no version; or
2. Simply do not support the concept of 'no version', given `agents` is an API that is designed only to be used by Ably SDKs, which will always have a version (we can refine the spec to make this clear).

I think my preference would be option 2 (YAGNI).

**Comment by lawrence-forooghian** [comment]
I'm going to go for option 1 of the above, due to Owen’s valid point re my spec change: https://github.com/ably/specification/pull/112#pullrequestreview-1179043377.

I've implemented this in https://github.com/ably/ably-cocoa/pull/1529.

(I've used pointer identity with a specific sentinel value instead of a zero-length value, as I believe this is more consistent with other Cocoa APIs, not that I can think of one off the top of my head, but that's just an implementation detail.)
