### ISSUE TITLE
App Store publication issues when using Carthage

### ISSUE THREAD

**Issue by bhargavbajani** [ably/ably-cocoa#1559]
There're a few issues with publishing to App Store if you add Ably through.

The app builds and runs but when you're making an archive and uploading it to App Store it won't be validated. Errors while validating: `CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.remyvirin.msgpack-iOS' under the iOS application 'XXXXXX.app'. With error code STATE_ERROR.VALIDATION_ERROR.90685 for id 042b0740-7b7f-4012-a121-ee888e479aa9`

this is a similar issue https://github.com/ably/ably-cocoa/issues/698

The framework contains a duplicate framework 

![](https://user-images.githubusercontent.com/13344552/205957347-96a15ff9-9654-43fc-bc99-7dfd4cff9d84.png)

### Which version of the Ably SDK are you using? 
>= 1.2.26 (Not sure about previous versions)

### On which platform does the issue happen? 
iOS

### Are you using Carthage? 
0.38.0

### Which version of Xcode are you using? 
XCode 13.4.1

**Comment by iOSDev-Auction** [comment]
Any update?

**Comment by maratal** [comment]
Thanks @bhargavbajani, we are looking into it.
