### ISSUE TITLE
TextProxyTransport.protocolMessagesSent messages are not in sync 

### ISSUE THREAD

**Issue by ikbalkaya** [ably/ably-cocoa#1561]
Our integration tests use `TextProxyTransport.protocolMessagesSent ` to verify messages sent through transport, however it looks like this won't keep messages correctly all the times.

Please check this [commit](https://github.com/ably/ably-cocoa/pull/1496/commits/38ad3a523a6a4c4fe87482c30b0a37fab19a1a4f) and comment on top of skipped test. 

I was able to confirm that 5 `.presence` actions are appended to the instance that keeps track of `protocolMessagesSent`, but still at the time of calling, it will return only 3 messages, which means it discards (or doesn't count) messages after reconnection somehow.

**Comment by maratal** [comment]
This was fixed [here](https://github.com/ably/ably-cocoa/commit/2fb7d5a7403aec90aef212fab1d93e66f9904177)
