### ISSUE TITLE
Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_DEFAULT. Investigate ways to avoid priority inversions

### ISSUE THREAD

**Issue by lighthouse-beacon-01** [ably/ably-cocoa#1569]
### Which version of the Ably SDK are you using? 
PODS:

* Ably (1.2.1):
  * AblyDeltaCodec (= 1.2.0)
  * KSCrashAblyFork (= 1.15.20-ably-6)
  * msgpack (= 0.3.1)
  * SAMKeychain (= 1.5.3)
  * SocketRocketAblyFork (= 0.5.2-ably-7)
  * ULID (= 1.1.0)
* AblyDeltaCodec (1.2.0)

### On which platform does the issue happen? 
iOS 13.1.3 to iOS 16.2

### Are you using Carthage? 
No

### Are you using Cocoapods? 
Yes, 1.11.3

### Which version of Xcode are you using? 
14.0.1 on M1 mac

### What did you do?
I'm getting a Hang Risk warning on Xcode on one of the dependency pods for Ably regarding the usage of dispatch_group_wait primitive (https://developer.apple.com/documentation/xcode/diagnosing-performance-issues-early)
![image](https://user-images.githubusercontent.com/122559202/212143381-8b18a143-c0ed-4753-a5d3-f129c0f79857.png)
![image](https://user-images.githubusercontent.com/122559202/212143553-29a31d67-1826-4206-ba91-25bca95c2333.png)

We've linked this to crashes that we've been experiencing since about 6 to 7 months ago with "C++ Exception: ARTException"

Does anyone have an idea of maybe what I might be doing wrong? or if this is a known issue?
I saw that the latest version of the SDK is 1.2.19 but I tried updating it to that and Cocoapods throws me an error saying that it can't be found
![](https://user-images.githubusercontent.com/122559202/212151187-6d49833f-6a80-4c94-a7f1-7498079cb305.png)

**Comment by maratal** [comment]
This was fixed in [v1.2.18](https://github.com/ably/ably-cocoa/releases/tag/1.2.18)
Couldn't you post your Podfile here? (at least the line with the ably-cocoa) @lighthouse-beacon-01

**Comment by maratal** [comment]
@lighthouse-beacon-01 you need to run one of these: `pod repo update` or `pod install --repo-update`
