### ISSUE TITLE
CI fails due to outdated dependencies for `xcparse`

### ISSUE THREAD

**Issue by maratal** [ably/ably-cocoa#1572]
A number of compiling errors like:
```
[55/94] Compiling TSCUtility ArgumentParser.swift
/Users/runner/work/ably-cocoa/ably-cocoa/xcparse/.build/checkouts/swift-tools-support-core/Sources/TSCUtility/FSWatch.swift:848:15: error: cannot assign value of type 'Thread' to type 'Thread?'
                self.thread = thread
                            ^
```
F.e. [here](https://github.com/ably/ably-cocoa/actions/runs/4277404094/jobs/7446190649)

Build scripts fails here:
https://github.com/ably/ably-cocoa/blob/8cafe328ba6520129da2632ac050422df8b06778/Scripts/upload_test_results.sh#L160-L163

**Comment by lawrence-forooghian** [comment]
Is this still an issue @maratal?

**Comment by lawrence-forooghian** [comment]
No longer an issue.
