### ISSUE TITLE
App crash on Ably close

### ISSUE THREAD

**Issue by fbarbat** [ably/ably-cocoa#1715]
### Which version of the Ably SDK are you using? 
1.2.19

### On which platform does the issue happen? 
macOS 13.3.1

### Are you using Carthage? 
No

### Are you using Cocoapods? 
No (We are using SPM)

### Which version of Xcode are you using? 
14.2

### What did you do?
Added this line of code to our project.

```
activeAbly?.close()
```

Then:

1. Create an Ably instance
1. Use a tool to block internet access to the app (for example, Little Snitch)
1. Destroy the Ably instance using close
1. Turn off wifi. The app will crash immediately here.

### What did you expect to happen?
The app not to crash and not to leak memory after calling close.

### What happened instead?
The app crashes sometimes in prod. If following the repro steps, it always crashes.

We saw that you might have fixed this in https://github.com/ably/ably-cocoa/pull/1565/files
However, last release (1.2.19) was released in Dec 8, 2022 and this fix was merged on Mar 27, 2023.
When are you shipping a new release?

Thank you.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4542) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
@fbarbat You can now try version 1.2.20.
