### ISSUE TITLE
App build fails due to missing dependencies

### ISSUE THREAD

**Issue by hansemannn** [ably/ably-cocoa#1755]
### Which version of the Ably SDK are you using? 
1.2.20

### On which platform does the issue happen? 
iOS 16.4

### Are you using Carthage? 
Yes, 0.38.0

### Are you using Cocoapods? 
Yes, 1.11.3

### Which version of Xcode are you using? 
14.3

### What did you do?
The build fails when including the framework - tried with the attached framework via Github releases, Carthage and Cocoapods.
<img width="1009" alt="Screenshot 2023-06-08 at 10 39 57" src="https://github.com/ably/ably-cocoa/assets/10667698/39c2287c-8463-4903-8192-bd0711751256">

> 'ARTTypes.h' file not found

### What did you expect to happen?
The build should succeed.

### What happened instead?
The build should fails with the above error message.

**Comment by hansemannn** [comment]
Workaround: Manually fix the imports (the ARTTypes.h is a public header but referenced from private headers).

```diff
- #import "ARTTypes.h"
+ #import <Ably/ARTTypes.h>
```

**Comment by hansemannn** [comment]
Workaround for now: Fix the invalid reference of headers inside private headers by using a module-based import:

```diff
- #import "ARTTypes.h"
+ #import <Ably/ARTTypes.h>

**Comment by maratal** [comment]
Hey @hansemannn Couldn't you test the branch from this PR https://github.com/ably/ably-cocoa/pull/1756 whether it works for you. Thanks.

**Comment by hansemannn** [comment]
@maratal Looks promising! This should work, thank you!

**Comment by hansemannn** [comment]
As the workaround to manually fix the import worked, so project is completed for now. A simple Swift-based project that uses manual framework inclusion (no SPM or Cocoapods) should reproduce it. If I get some additional time, I'll try to provide the project as well

**Comment by maratal** [comment]
Should be now fixed https://github.com/ably/ably-cocoa/pull/1801

**Comment by maratal** [comment]
It wasn't - https://github.com/ably/ably-cocoa/issues/1824
