### ISSUE TITLE
App is crashing with reason : dyld[64150]: Symbol not found: _OBJC_CLASS_$_NSError in XCode 15 - iOS 17 

### ISSUE THREAD

**Issue by NagarajuKamatham** [ably/ably-cocoa#1803]
### Which version of the Ably SDK are you using? 
`1.2.20`

### On which platform does the issue happen? 
E.g. `iOS17`

### Are you using Carthage? 
No

### Are you using Cocoapods? 
yes, pod version 1.11.3

### Which version of Xcode are you using? 
XCode version : 15

App is crashing with below error, when launch the App.
 dyld[64150]: Symbol not found: _OBJC_CLASS_$_NSError

**Comment by maratal** [comment]
Fixed in https://github.com/ably/ably-cocoa/releases/tag/1.2.21
