### ISSUE TITLE
App crash at startup

### ISSUE THREAD

**Issue by simon-feamzy** [ably/ably-cocoa#1814]
### Which version of the Ably SDK are you using? 
1.2.20

### On which platform does the issue happen? 
iOS15.5

### Are you using Carthage? 
no

### Are you using Cocoapods? 
1.13.0

### Which version of Xcode are you using? 
(`xcodebuild -version`)

### What did you do?
Start app

### What did you expect to happen?
Describe the expected outcome.

### What happened instead?
App crash immediately

```
dyld[31309]: Symbol not found: _OBJC_CLASS_$_NSError
  Referenced from: /Users/simon/Library/Developer/CoreSimulator/Devices/AC930872-7A69-4986-A61F-D8AB5666F41F/data/Containers/Bundle/Application/BF8F25E6-9BE9-489E-93A0-0A784F6A0A0B/App.app/App
  Expected in: /Users/simon/Library/Developer/CoreSimulator/Devices/AC930872-7A69-4986-A61F-D8AB5666F41F/data/Containers/Bundle/Application/BF8F25E6-9BE9-489E-93A0-0A784F6A0A0B/App.app/Frameworks/Ably.framework/Ably
```

**Tip:** set the log level to debug. E.g. `realtime.logger.logLevel = .debug` and take a look at our [troubleshooting guide](https://support.ably.io/solution/articles/3000063743-guide-information-we-need-to-help-you-diagnose-problems)

### Link to sample project
Feel free to link to a sample project that showcases the issue.

**Comment by maratal** [comment]
This was fixed in the [latest release](https://github.com/ably/ably-cocoa/releases/tag/1.2.21). @simon-feamzy

**Comment by simon-feamzy** [comment]
Thanks a lot
