### ISSUE TITLE
App build fails due to missing dependencies (xcode 15.0.1)

### ISSUE THREAD

**Issue by bhargavbajani-simformsolutions** [ably/ably-cocoa#1824]
### Which version of the Ably SDK are you using? 
Version `[1.2.21](https://github.com/ably/ably-cocoa/releases/tag/1.2.21)` 

### On which platform does the issue happen? 
`iOS17`

### Are you using Carthage? 
Yes, github "ably/ably-cocoa" "1.2.21"

### Which version of Xcode are you using? 
yes, Xcode 15.0.1

### What did you do?
The build fails when including the framework - tried with the attached framework via Github releases, Carthage.
![image](https://github.com/ably/ably-cocoa/assets/63727314/b5d8691b-835c-458d-bae4-8a31b8cf6a6a)

'ARTTypes.h' file not found

### Command used to install a framework
carthage update ably-cocoa --use-xcframeworks --no-use-binaries --platform iOS

### What did you expect to happen?
The build should succeed.

### What happened instead?
The build should fail with the above error message.

**Comment by bhargavbajani-simformsolutions** [comment]
@maratal  It's not possible for now due to project limitations.

**Comment by maratal** [comment]
@lawrence-forooghian shouldn't we give this another shot? https://github.com/ably/ably-cocoa/pull/1756

**Comment by maratal** [comment]
It is now fixed in https://github.com/ably/ably-cocoa/releases/tag/1.2.23 @bhargavbajani-simformsolutions
