### ISSUE TITLE
[NSNull unsignedLongLongValue]: unrecognized selector sent to instance 0x210ee20b0"

### ISSUE THREAD

**Issue by imguna06-Tfe** [ably/ably-cocoa#1837]
[NSNull unsignedLongLongValue]: unrecognized selector sent to instance 0x210ee20b0"

try to connect ably app will be crashed

Pod version - 1.2.23
Xcode version - 15.0
deployment version - 13.0

**Comment by maratal** [comment]
Hey @imguna06-Tfe couldn't you provide us the full crash report?

**Comment by maratal** [comment]
The only place where we call `unsignedLongLongValue` is getting a "ttl" value while token creation from JSON dictionary, is there a chance you've included "NSNull" instead of just omitting "ttl"?

**Comment by imguna06-Tfe** [comment]
Thanks...it is working fine after change the ttl key value
