### ISSUE TITLE
Update CONTRIBUTING.md to use Github `Generate release notes` button

### ISSUE THREAD

**Issue by maratal** [ably/ably-cocoa#1881]
[This button](https://github.com/ably/ably-cocoa/releases/new) does pretty much the same thing as the `github_changelog_generator` script described now in the CONTRIBUTING guide. No need for this script anymore since this functionality is now built-in.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4640) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
Recent similar discussion - https://ably-real-time.slack.com/archives/C03JDBVM5MY/p1713542539425589
Owen somehow managed to do that in ably-js.

**Comment by lawrence-forooghian** [comment]
Ah cool, seems like you can type in a dummy tag name in the "choose a tag" field 👍
