### ISSUE TITLE
Thread priority inversion runtime warning

### ISSUE THREAD

**Issue by umair-ably** [ably/ably-cocoa#1897]
New SDK v1.2.26 release seems to have introduced a regression in which the thread priority is inverted, which throws a warning at runtime. 

![image](https://github.com/ably/ably-cocoa/assets/157486912/c3ebce65-d9ea-414f-b3fa-68967cbbf9b7)

Similar to https://github.com/ably/ably-cocoa/issues/1516

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/ECO-4717) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
I’m assigning a high priority to this bug since it presumably affects all of the users who are compiling our library, which I think is most of our users. And it might cause people to question the quality of our SDK.
