### ISSUE TITLE
Implement RTP18a

### ISSUE THREAD

**Issue by maratal** [ably/ably-cocoa#1904]
[RTP18a](https://sdk.ably.com/builds/ably/specification/main/features/#RTP18a): _The client library determines that a new sync has started whenever a SYNC ProtocolMessage is received with a channel attribute and a new sync sequence identifier in the channelSerial attribute. The channelSerial is used as the sync cursor and is a two-part identifier <sync sequence id>:<cursor value>. If a new sequence identifier is sent from Ably, then the client library must consider that to be the start of a new sync sequence and any previous in-flight sync should be discarded_

Now library doesn't support this behavior (in-flight sync will not be discarded, instread new sync will be [ignored](https://github.com/ably/ably-cocoa/blob/2f6cc1e73ccfd5a8e22139d2ce6132a0432adcd3/Source/ARTRealtimePresence.m#L725)).

This issue is a part of a bigger work (https://github.com/ably/ably-cocoa/pull/1891).

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4738) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
> I’m setting this as a medium priority but it’s a bit of a guess — I don't know how often the described scenario occurs in reality.

I agree! All other libraries are working fine without implementing this. Event if `ably-js` supports this spec, being single threaded, there's no issue of synchronization or multithreading unlike other languages.

**Comment by maratal** [comment]
> > I’m setting this as a medium priority but it’s a bit of a guess — I don't know how often the described scenario occurs in reality.
> 
> I agree! All other libraries are working fine without implementing this. Even if `ably-js` supports this spec, being single threaded, there's no issue of synchronization or multithreading unlike other languages.

There are no threading issue in this PR though (all happens in the single realtime background thread). Should I close it now or just leave it as-is?

**Comment by lawrence-forooghian** [comment]
It seems like something we should implement; why would we close it?

**Comment by maratal** [comment]
> It seems like something we should implement; why would we close it?

Sorry, I've meant the PR, not clear to me what to do with it now. Shouldn't be permanently opened, right? If you can help in reviewing it I would appreciate.

**Comment by sacOO7** [comment]
@maratal few points to mention
1. Even though this spec is not implemented in other SDKs, we haven't faced any issues due to lack of it.
2. Spec is a bit complicated and involves a very rare scenario that's unlikely to happen.
3. If we do not implement this spec correctly, I'm afraid, it will break existing spec instead of improving it.

Because of this, I think we should hold on to merging it into the main. Maybe in the future, we can think about merging it. Let's see the feedback from customers about recently merged PR's first 👍
