### ISSUE TITLE
Add the rest of swift concurrency annotations

### ISSUE THREAD

**Issue by maratal** [ably/ably-cocoa#1971]
Continuation of https://github.com/ably/ably-cocoa/issues/1962

Some types were not added because it's not obvious what should be added from the glance. I suggest to keep this issue open and add types that causing compilation errors in this description (meanwhile adding them to [Ably+Dependencies.swift](https://github.com/ably-labs/ably-chat-swift/blob/main/Sources/AblyChat/AblyCocoaExtensions/Ably%2BDependencies.swift) to add them all at once later in ably-cocoa):

`ARTRealtimePresenceQuery`

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4968) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
If there are still types that we know need to be added, we should do this before doing a release.

**Comment by maratal** [comment]
> If there are still types that we know need to be added, we should do this before doing a release.

https://github.com/ably/ably-cocoa/pull/1973

**Comment by maratal** [comment]
@umair-ably couldn't you post screenshots of the warnings/errors with `ARTRealtimeChannelOptions` and `ARTChannelProperties` you've mentioned in [this](https://github.com/ably/ably-cocoa/pull/1973) PR? I've also faced an error with the `properties` member in `final class Channel: RealtimeChannelProtocol`, but declaring it as a readonly getter solved the problem.
