### ISSUE TITLE
Consider not holding references to children objects

### ISSUE THREAD

**Issue by tcard** [ably/ably-cocoa#607]
Right now, this causes a crash:

```swift
var channel: ARTChannel
{
    var rest = ARTRest(key: "...")
    channel = rest.channels.get("foo")
    // rest is deallocated here, since channel only holds a weak ref to it,
    // so its refcount = 0 when the rest var goes out of scope
}
channel.publish(...) // crash here; channel's internal reference to rest is nil!
```

Or just:

```swift
ARTRest(key: "...").channels/* rest deallocated at this point */.get("foo")/* crash here */.publish(...)
```

This is because we're following the pattern of parents creating instances of children, usually at startup (e. g. `rest.channels`, `rest.auth`, `realtime.connection`...), and those children having the parent as a dependency, so they refernce the parent too. To avoid a reference-count cycle that would memory leak, we (correctly) reference the parent objects weakly, ie. not incrementing their reference counts. The problem is that this weak reference can in fact outlive the strong one it copies from.

Instead of using weak refs, we can just not have references from parents to children, and instead allocate new instances each time they're asked for, in the getter. The children would then keep strong references to their parents, and then follow the behavior you'd expect from a GCd language.

Any state children "singleton" objects may have can be stored in the parent instead. For a non-trivial example, `realtime.channels` needs to store its channels somewhere so that you get the same ones, with the same `state` and everything, in each `realtime.channels` instance. So it should store them in `realtime`.

**Comment by mattheworiordan** [comment]
> To avoid a reference-count cycle that would memory leak, we (correctly) reference the parent objects weakly, ie. not incrementing their reference counts. 

I don't follow.  Why do we have a weak reference from a Channel to the Rest/Realtime Client when as far as I can tell, it depends on it?

**Comment by tcard** [comment]
@mattheworiordan They depend on each other. The channel depends on REST/Realtime and REST/Realtime depends on the channel (indirectly, through the `.channels` collection).

In a typical GCd language you can just model this with a straightforward reference cycle. But in iOS there's no GC but [Automatic Reference Counting](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/AutomaticReferenceCounting.html#//apple_ref/doc/uid/TP40014097-CH20-ID48), in which cycles like this necessarily cause leak. So you mark one of the references as weak (ie. it doesn't increase the reference count of the referee) and then enforce the invariant that children must not outlive their parents (ie. when the parent's ref count reaches 0 and is deallocated, the children must not be reachable).

I'm arguing that we're not really enforcing this invariant, since users can hold references to children (channels, `rest.auth`, etc.) directly (and we want them to!). So we should model these dependency cycles in some other way (I argue, by not having parents depend on long-lived children, but create them each time they're needed, and holding their state for them).

**Comment by tcard** [comment]
Well, I don't see the point when we can just _not_ have an error.

I've thought a bit more about this and I might have a better solution. Instead of children depending on the parent, and the parent holding up to all their state, which is kind of cumbersome, have a "inner" parent object, and have the client object be just a collection-like for its children, which wouldn't depend on it, but on the parent object.

So currently we have this:

```

----- = strong reference
- - - = weak reference

+------------+              +-------------------+
|  Realtime  |   channels   | Channel           |
|            |------------->| .state            | 
| websocket  |              | .name             |
| queues     |              | (listeners, etc.) |
| conn state |< - - - - - - |                   |
+------------+              +-------------------+
```

And I proposed this (roughly):

```
+-----------------------+              +--------------------+           
|  Realtime             |              | Channel            |
|                       |<-------------| (stateless proxy   |
| +-------------------+ |              | object for private |
| | Channel (private) | |              | channel)           |
| | .state            |<---------------|                    |
| | .name             | |              |                    |
| | (listeners, etc.) | |              +--------------------+
| +-------------------+ |
| ... other private     |
| channels ...          |
+-----------------------|
```

But I think this would be probably easier to refactor to, and also less verbose and more efficient:

```
+------------+              +-------------------+
|  Realtime  |   channels   | Channel           |
|            |------------->| .state            | 
|            |              | .name             |
|            |              | (listeners, etc.) |
|            |              |                   |
+------------+              +-------------------+
      |                              |
      |                              |
      |       +------------+         |
      |       | websocket  |         |
      +------>| queues     |<--------+
              | conn state |
              +------------+
```

**Comment by mattheworiordan** [comment]
Ok, so just to be clear then:

* If a reference to the client/connection was lost (for the dev consuming this API), they would have no means to access the object again as it's not exposed from the Channel object or any of it's children.
* So long as a ref to Realtime / Channel is kept, the reference counters will prevent them being disposed.  However, as soon the Realtime & Channel refs are both gone, Realtime & Channel should be disposed right?  I assume that's because the ref count for Realtime would be zero, which means it would be disposed of, which in turn would leave all the Channel objects with zero references meaning they too are disposed, finally leaving the WS / connection state with zero references too?

That sounds sensible but worried about how much work this is for a problem we know could affect customers, but at present has not been reported?

**Comment by tcard** [comment]
> If a reference to the client/connection was lost (for the dev consuming this API), they would have no means to access the object again as it's not exposed from the Channel object or any of it's children.

Right. This is less of a corner case for REST, I think, since it's stateless. You can make one-off instances of REST and just take a channel, for example.

> So long as a ref to Realtime / Channel is kept, the reference counters will prevent them being disposed. However, as soon the Realtime & Channel refs are both gone, Realtime & Channel should be disposed right? I assume that's because the ref count for Realtime would be zero, which means it would be disposed of, which in turn would leave all the Channel objects with zero references meaning they too are disposed, finally leaving the WS / connection state with zero references too?

Yes, just as in any normal GCd language as long as there are no reference cycles.

> That sounds sensible but worried about how much work this is for a problem we know could affect customers, but at present has not been reported?

Sure, it's not a terribly critical issue. But since the code is going to go through a major review for thread-safety anyway, this could sneak at the same time.

**Comment by mattheworiordan** [comment]
> Right. This is less of a corner case for REST, I think, since it's stateless. You can make one-off instances of REST and just take a channel, for example.

Sure, but it would feel odd to have two different models.  Additionally, it's not completely stateless. For example a channel is instances with options which affect how it decrypts messages.

> Sure, it's not a terribly critical issue. But since the code is going to go through a major review for thread-safety anyway, this could sneak at the same time.

Ok, how's that going?

**Comment by funkyboy** [comment]
@mattheworiordan I think this has been addressed [here](https://github.com/ably/ably-ios/pull/620). Right?

**Comment by mattheworiordan** [comment]
> @mattheworiordan I think this has been addressed here. Right?

@funkyboy to be honest I don't know without reading all the work done in https://github.com/ably/ably-ios/pull/620.  If you think it's addressed, then do close this.

**Comment by tcard** [comment]
Closing this as I'm finally addressing this problem as part of the solution for #879. Discussion follows there.
