### ISSUE TITLE
my-members presenceMap requirement change for 1.1

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-cocoa#737]
See https://github.com/ably/docs/pull/446

**Comment by SimonWoolf** [comment]
@ricardopereira Just want to check in on the status of this? Bit worried that this issue seems to be left open after the 1.1 release -- as noted in the linked docs pr, the server assumes that any client library that sends `v=1.1` implements the local presence map up to spec

**Comment by ricardopereira** [comment]
@SimonWoolf Ok, I will look at it and after this I'll review all the remaining issues and see if something else is missing. Thanks
