### ISSUE TITLE
Add idempotent REST publishing

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-cocoa#749]
See spec at https://github.com/ably/docs/pull/473

Ruby implementation at https://github.com/ably/ably-ruby/pull/165

Whilst this is technically 1.1 functionality, we can add this now so long as idempotent publishing is disabled by default.

**Comment by mattheworiordan** [comment]
Spec is now finalised, and all functionality to support this will be available in `sandbox` from next week.  We should implement this now.

**Comment by ricardopereira** [comment]
@mattheworiordan Is this available in `sandbox`?

**Comment by paddybyers** [comment]
@ricardopereira `dev` at the moment
