### ISSUE TITLE
Add Transient publishing

### ISSUE THREAD

**Issue by ricardopereira** [ably/ably-cocoa#787]

**Comment by ricardopereira** [comment]
@mattheworiordan Could you please add some information about this?

**Comment by mattheworiordan** [comment]
You created the issue, so shouldn't you? 😄 

See https://github.com/ably/docs/pull/323

**Comment by ricardopereira** [comment]
@mattheworiordan Didn't know where to look 🙄 You're right. I was lazy. Thanks man 😄

**Comment by ricardopereira** [comment]
@funkyboy I saw your #793 but I was starting to implement this. Are you doing the same?

**Comment by funkyboy** [comment]
@ricardopereira no. That PR was just meant to add the new values to the enum.
