### ISSUE TITLE
Compile SocketRocket with main library

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-cocoa#805]
SocketRocket is no longer actively maintained.  Whilst it is a very stable, it has recently introduced issues:

* [Issue with AppStore](https://github.com/ably/ably-ios/issues/803)
* [Warnings showing up in builds](https://github.com/ably/ably-ios/issues/688)

We'll need to make sure it doesn't get in the way of [macOS support](https://github.com/ably/ably-ios/issues/460)

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-377) by [Unito](https://www.unito.io)

**Comment by ricardopereira** [comment]
New NSURLSession is introducing WebSockets 🙌 (in betas iOS/tvOS 13, macOS 10.15)

https://developer.apple.com/documentation/foundation/nsurlsession/3181171-websockettaskwithurl?language=objc

**Comment by mattheworiordan** [comment]
@QuintinWillison what's your view on what to do with this?  If I recall, a more modern option is https://github.com/daltoniam/Starscream.

**Comment by QuintinWillison** [comment]
@mattheworiordan Never heard of Starscream, but it would not help here as it's written in Swift. I wouldn't have faith in Jetfire either (apparently their Objective-C 'counterpart' to Starscream) as that's not being maintained.

So, @ricardopereira's suggestion would be the right way to go. Unfortunately iOS 13 has only been out a few months. We could consider having a runtime branch in the code so apps running pre-iOS-13 continue to use SocketRocket but that adds testing and support complexity in the short to medium term.

**Comment by jamienewcomb** [comment]
@maratal we have a PR open for this #1090 . would be great if you can pick this up and review the PR. we feel it may not be complete

**Comment by QuintinWillison** [comment]
I think to clarify @jamienewcomb's comment above, the work done in that PR is likely complete but because it's been left for so long then it is likely to have drifted away from being immediately landable (i.e. needs `main` merged in and checks run, etc..). More eyes on the work will be helpful to in order to make sure it's still current enough to be worth landing with the outcome being that the codebase moves forward positively.
