### ISSUE TITLE
Add support for remembered REST fallback host

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-cocoa#815]
See https://github.com/ably/docs/pull/554

We need to add this functionality to all client libraries, but prioritise the server-side ones given they are more affected if a single DC is offline and they are publishing at a high rate.

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-378) by [Unito](https://www.unito.io)

**Comment by maratal** [comment]
Implemented here https://github.com/ably/ably-cocoa/pull/1150
