### ISSUE TITLE
Idempotent publishing is not enabled in the upcoming 1.1 release

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-cocoa#816]
See https://github.com/ably/docs/pull/568

We must ensure that that idempotent is not yet enabled by default and requires the user to explicitly enable.

Related to #749

**Comment by ricardopereira** [comment]
Idempotent Publishing is still waiting for review: #786

**Comment by ricardopereira** [comment]
Done https://github.com/ably/ably-cocoa/pull/786/commits/69aa35861bf60c0eb71c392d343a440add5f485c
