### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by ricardopereira** [ably/ably-cocoa#819]
Add support for the [Swift PM](https://swift.org/package-manager/).

Acceptance Criteria: 
- `ably-cocoa` available to customers via Swift Package Manager

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-379) by [Unito](https://www.unito.io)

**Comment by makoni** [comment]
any plans for Swift PM?

**Comment by QuintinWillison** [comment]
Hello @makoni and thanks for commenting. This item is very much alive in our backlog, however we're still gauging the level of interest from developers in order that we can give it appropriate prioritisation.

Can you give us any more detail around your use case?

**Comment by makoni** [comment]
I'm using it in iOS app for events. Right now Swift Package Manager is included in Xcode and it would be nice to have it's support :)

**Comment by makoni** [comment]
any updates?

**Comment by QuintinWillison** [comment]
Sorry, @makoni - we've not done any work on this, nor has it been prioritised to work on in the near future.

This would, clearly, be much easier to "just do" if our codebase were pure Swift. Unfortunately that's not the case so we need to make sure we fully understand what this involves and how to make it happen. I'm going to try to push those conversations forward here at Ably as part of the ongoing, wider process we have around planning work that will increase our developer experience.

Thanks for chasing this. 🙂

**Comment by makoni** [comment]
@QuintinWillison the project doesn't have to be pure Swift. As an example: One Signal SDK is Objective-C project and they've added Swift PM support recently. It might be a good reference :)

https://github.com/OneSignal/OneSignal-iOS-SDK

**Comment by makoni** [comment]
One more example of Objective-C project that added Swift Package Manager support recently:
https://github.com/BranchMetrics/ios-branch-deep-linking-attribution

**Comment by benjamincombes** [comment]
Any news on this? I use 25+ libs, all are on SPM that is now really standard, I was planning to replace Pusher with Ably, but unfortunately I won't start using Cocoapods again just for it... Hope that it could be supported soon so that I can drop Pusher 🙏 !

**Comment by QuintinWillison** [comment]
Hello @makoni and @benjamincombes ... I hear you and thank you for the nudges. I'm prioritising this up our backlog. We need to ramp up the activity in this repository and that is also high on our list.

**Comment by benjamincombes** [comment]
Thanks @QuintinWillison, hope this could be done soon so that we can enjoy all the benefits of Ably over Pusher on our project, can't wait for it!

**Comment by QuintinWillison** [comment]
See also #1070.

**Comment by QuintinWillison** [comment]
We've been discussing this in our estimation session this morning and the question around _where_ the releases to SPM are made from came up. We concluded that it is acceptable for the outcome of work done on this issue to be that we continue to release from a developer's workstation. As such we will create a follow up issue to move this work, once done, forwards to release from CD (i.e. GitHub workflows).
