### ISSUE TITLE
GA push documentation review

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-cocoa#825]
@ricardopereira please see https://github.com/ably/docs/pull/581.  The push docs are now up to date, and @tomczoink will be adding some additional API docs to the Realtime / REST API docs at www.ably.io/documentation.

Would you mind reviewing the following pages in the PR above to confirm the iOS docs are correct?

* [x] https://ably-docs-pr-581.herokuapp.com/general/push/
* [x] https://ably-docs-pr-581.herokuapp.com/general/push/publish
* [x] https://ably-docs-pr-581.herokuapp.com/general/push/admin

**Comment by mattheworiordan** [comment]
@ricardopereira we plan on releasing this quite soon, so if you have time to review soon we'd appreciate it.

**Comment by ricardopereira** [comment]
@mattheworiordan "Activating devices from your server" section in http://ably-docs-pr-581.herokuapp.com/general/push/activate-subscribe/ is missing the iOS steps to use the custom register methods.

Should I open a PR in Docs and add that information?

**Comment by paddybyers** [comment]
@ricardopereira yes pls
