### ISSUE TITLE
Review Push documentation on website

### ISSUE THREAD

**Issue by tomczoink** [ably/ably-cocoa#837]
Currently we have documentation on push on the website, however this hasn't been reviewed by each respective library maintainer. This needs to be done for the following pages:

https://www.ably.io/documentation/general/push
https://www.ably.io/documentation/general/push/publish
https://www.ably.io/documentation/general/push/activate-subscribe
https://www.ably.io/documentation/general/push/admin

Anything wrong/needing addition please add to this issue, and I'll make sure to update the docs accordingly.

**Comment by ricardopereira** [comment]
@tomczoink Done 👍
