### ISSUE TITLE
Expose Auth.tokenDetails

### ISSUE THREAD

**Issue by paddybyers** [ably/ably-cocoa#852]
We're planning to expose a public way to discover the current token in use by the library - see https://github.com/ably/docs/pull/673.

How easy is it to implement this now for iOS?

**Comment by ricardopereira** [comment]
@paddybyers Quite easy, that property already exist but it's hidden.

**Comment by ricardopereira** [comment]
Sure, I'll add this in the next release. I'll prepare it today.
