### ISSUE TITLE
Interactive push test app & instructions

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-cocoa#872]
See https://github.com/ably/ably-java/issues/486 and https://github.com/ably/AndroidPushExample.

Given push tests need to be tested interactively with an actual device, we should make sure we have an app with the same functionality and instructions on how to test the app, along with details in the README of this repo.  This may exist in https://github.com/ably/push-test-ios.

@paddybyers can you please make sure @ricardopereira knows what is needed to ensure we have consistent interactive push testing.

**Comment by ricardopereira** [comment]
@Srushtika is handled this in https://github.com/ably/iOSPushExample.
