### ISSUE TITLE
Push deactivate on an app is failing with`push-subscribe` permissions

### ISSUE THREAD

**Issue by Srushtika** [ably/ably-cocoa#873]
### Which version of the Ably SDK are you using? 
`1.1.7`

### On which platform does the issue happen? 
`iOS12.1`

### Are you using Carthage? 
No

### Are you using Cocoapods? 
Yes, v1.7.3

### Which version of Xcode are you using? 
Xcode 10.2.1
Build version 10E1001

### What did you do?
Have been testing the [push iOS application](https://github.com/ably/push-example-ios) with `push-admin` and `push-subscribe` permissions.

### What did you expect to happen?
The app works as expected when it has `push-admin` permissions (assigned by the auth server). When I switch the permissions to `push-subscribe`, except for publishing push notifications, the rest of the functionality (i.e activation, deactivation, subscription, etc) is expected to work as before

### What happened instead?
The `deactivate()` method failed every time when the app had `push-subscribe` permissions. As soon as I switched the permissions to `push-admin` (via the auth server without even touching the app), the deactivate method worked as expected. The following is the error in the log on clicking the button triggering the `deactivate()` method:

```
handleAblyPushDidDeactivate(notification:) with error 2019-07-12 10:31:52.948739+0100 push-interactive-app[964:227867] transition: ARTPushActivationStateWaitingForDeregistration -> ARTPushActivationStateWaitingForDeregistration
ARTErrorInfo with code 40160, message: action not permitted, app = ye-rkQ. (See https://help.ably.io/error/40160 for help.), reason: (null)
```

### Link to sample project
https://github.com/ably/push-example-ios

**Comment by ricardopereira** [comment]
Fixed with https://github.com/ably/ably-cocoa/pull/871
