### ISSUE TITLE
Inclusion error generates warnings

### ISSUE THREAD

**Issue by paddybyers** [ably/ably-cocoa#914]
Problem:

> I’m trying to clean up and remove all build warning messages from our project.  I wasn’t able to find any reason for these conflict warning messages.  Do you have any thoughts that might help us remove these?

![image](https://user-images.githubusercontent.com/1137574/67981579-e00eed00-fc18-11e9-8b2d-2906d241e22a.png)

Solution:

> This should be importing the header not the implementation.

![image](https://user-images.githubusercontent.com/1137574/67980341-257deb00-fc16-11e9-90e9-b27728119fca.png)

**Comment by ricardopereira** [comment]
@paddybyers This is already fixed in #905 but not released yet.

**Comment by paddybyers** [comment]
@ricardopereira thanks
