### ISSUE TITLE
Basic soak testing

### ISSUE THREAD

**Issue by tcard** [ably/ably-cocoa#915]
In order to confidently merge the significant changes that v1.1.11 brings, we want to make sure that it won't make apps crash.

After some discussion, I propose we run a soak test app before releases. This app should try to make the library do every combination of things it could possibly do for some extended period of time, so as to uncover possible situations that make the app crash.

The way to achieve this is that the app should, continuously, call every method exposed by the library, with random (both valid and invalid) arguments, in random order, with random delays in between calls. Interactions with external APIs such as Ably, APNS, etc. are mocked, and similarly behave randomly, but validly, with random latencies, and random externally-generated events (e. g. messages incoming from a channel, disconnects, etc.)

In order for this to be reproducible, all randomness should derive from a fixed seed. Running the app with the same seed again should make it behave the same way; this is doable because no external interaction actually happens.

This is a rather blunt approach, but more "formal" approaches would require a lot of work.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-605) by [Unito](https://www.unito.io)

**Comment by paddybyers** [comment]
I think this will work.

**Comment by QuintinWillison** [comment]
I agree that we should be able to do more downstream integration/soak testing of our SDKs, however this isn't a current priority and I can't see it becoming one anytime soon. This issue is over 3 years old and our collective understanding has moved on, so I don't believe this issue is adding value to our backlog now.
