### ISSUE TITLE
Missing events in soak tests

### ISSUE THREAD

**Issue by tcard** [ably/ably-cocoa#940]
#916 implemented the bulk of interesting events that may happen to the library.

Some missing are:

* [ ] Reauth.
  * [ ] Via `auth.authorize`.
  * [ ] Via server-sent `AUTH` protocol message.
* [ ] Server-initiated clean disconnection.
* [ ] Client-driven clean disconnect + reconnect with recovery key.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-606) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
Relates to an initiative we're not pursuing anymore. See https://github.com/ably/ably-cocoa/issues/941#issuecomment-1338852518
