### ISSUE TITLE
Run soak test as part of CI

### ISSUE THREAD

**Issue by tcard** [ably/ably-cocoa#941]
#916 attempted but fell short of running the soak test in CI via Firebase Test Lab. Instead, it just added a `soaktest` lane to Fastlane to be run manually.

CI can't be done reliably right now:

> Bad news: if the app crashes on Firebase Test Lab, the test is marked as successful anyway and you have to [manually go to the Firebase console](https://console.firebase.google.com/u/2/project/ably-cocoa-260210/testlab/histories/bh.ab732080b52eff17/matrices/7364230915804545275/executions/bs.294ed470fba5bfab/issues) to see that it actually crashes. I see no API to check this programmatically and I see no way around this.

![](https://user-images.githubusercontent.com/727422/69918105-47b19580-146e-11ea-9ed5-50ddb182db04.png)

I've opened a case with Firebase Test Lab support to look into this. Alternatively, we can consider other providers.

If we keep using Firebase, b830118bb25204c6d402fbc7540454ca841fa06c should be reverted to run the soak test on CI again.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-607) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
This issue is 3 years old and no work has been done on it. We've also made a lot of changes to the way tests are run since this issue was created, so I don't feel keeping this issue in the backlog has any value.
