### ISSUE TITLE
Agent should be ably-cocoa by default

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-cocoa#945]
I have not checked the code for this lib, but I think we send `ably-ios` as the agent, yet this library is now `ably-cocoa`.  We should I believe do the following:

* [x] Change default agent to `ably-cocoa`
* [x] Include a variant based on platform such as `macos`, `ios`, `watchos`, `ipados`.  Not sure what the official variants are, but assuming it was ios it would be `ably-cocoa.ios`
* [x] Check for legacy references in code to `ably-ios` and replace with `ably-cocoa`
* [ ] Make sure we have no references elsewhere in docs or the website to `ably-ios`

**Comment by tcard** [comment]
#954 does the parts of this that concern this repo.
