### ISSUE TITLE
iOS Incompatible library version crash - DYLIB_COMPATIBILITY_VERSION vs DYLIB_CURRENT_VERSION

### ISSUE THREAD

**Issue by RacingWang** [ably/ably-cocoa#946]
### Which version of the Ably SDK are you using? 
E.g. `1.1.13`

### On which platform does the issue happen? 
E.g. `iOS13`

### Are you using Cocoapods? 
1.8.4

### Which version of Xcode are you using? 
11.3

### What did you do?
My SDK can be installed by Cocoapods, and I set Ably as the dependency:
```
spec.dependency "Ably", "~> 1.1"
```
However, when my app runs after pod install, app would crash when launching:
```
Incompatible library version: 
M17SDK requires version 1.1.13 or later, but Ably provides version 1.0.0
```
So I downloaded Ably.framework on Github release and run this command to check:
```
otool -L Ably.framework/Ably 
```
I saw the dlyb version is incompatible.
```
@rpath/Ably.framework/Ably (compatibility version 1.1.13, current version 1.0.0)
```

### What did you expect to happen?
The current version should be the same with compatibility version (1.1.13).

### What happened instead?
1.0.0

**Comment by QuintinWillison** [comment]
I'm going to close this issue as I believe it's resolved in [1.1.14](https://github.com/ably/ably-cocoa/releases/tag/1.1.14). Feel free to re-open this issue, @RacingWang, if this is still causing you problems. Thanks!
