### ISSUE TITLE
REST-only library

### ISSUE THREAD

**Issue by paddybyers** [ably/ably-cocoa#992]
A customer has requested whether or not we could create REST-only library for cocoa. The aim would be to minimise footprint and, in particular, minimise the external dependencies. How easy would it be to do that?

**Comment by QuintinWillison** [comment]
Relates to #949

**Comment by QuintinWillison** [comment]
The basics of making a REST call from a Cocoa application (e.g. an iOS app) is simple and well understood by most developers. There are a few ways it can be done using Apple's foundation SDK (some for foreground execution and others for background via OS daemon), plus there are numerous third party libraries upon which some developers choose to depend upon as a layer on top of Apple's offerings.

What this customer is really looking for, as far as I understand, is help with publishing encrypted messages to Ably via our REST API. This really just needs some help with the encryption and Ably payload packaging, ready to go on the wire.

Therefore, given that the actual process of making the REST calls doesn't really need solving, all we are looking to help with is the Ably specific message packing. If a new library was just offering support in that area then, in addition, it could be of use to assist with MQTT, SSE and other applications where Ably's 'native' REST API is not being used to talk to Ably.

I think this may be able to be solved by producing a new pure Swift library that just offers synchronous methods to assist with these operations. I think we should also keep an eye on how it might interoperate with [Combine](https://developer.apple.com/documentation/combine) - this may require no work at all but worth prototyping with.

**Comment by QuintinWillison** [comment]
Speaking to @paddybyers just now about this and he pointed out that, in respect of adding support for decoding/unwrapping inbound Ably messages, beyond utility for SSE and MQTT applications there is also the valid use case of using the REST API to [retrieve message history](https://docs.ably.io/rest/history/).

**Comment by mattheworiordan** [comment]
> The aim would be to minimise footprint and, in particular, minimise the external dependencies. How easy would it be to do that?

How many people have asked for this?  
And why are dependencies an issue with Cocoa i.e. I assume this is for server-side use.
It would be good for us to track how many people need this and why before we do anything about it.

**Comment by paddybyers** [comment]
Personally I don't think there's sufficient demand and/or value in this to create a REST-only library. I suggest closing this issue. If @kavalerov you want to track this as a possible future feature, then go ahead, but there doesn't need to be an issue in this repo.

**Comment by kavalerov** [comment]
I am tracking this already in productboard (https://ably.productboard.com/feature-board/1237731-feature-organization/features/5898832/detail)

**Comment by kavalerov** [comment]
So ok ot close
